import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api } from './api';
type Project={id:string;name:string;domain:string|null};
type Snapshot={project:Project;counts:Record<string,number>;recentRuns:Array<{id:string;actor:string;command:string;status:string;createdAt:string;durationMs:number|null}>};
type KeywordRow={keyword:{id:string;text:string;source:string;status:string;avgMonthly:number|null};clusterId:string|null};
type ClusterRow={cluster:{id:string;title:string;intent:string};keywordCount:number};
type Task={id:string;title:string;status:string;assigneeType:string;priority:number};
type Decision={id:string;verdict:string;action:string;targetType:string;reason:string|null};
export function App(){
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[snapshot,setSnapshot]=useState<Snapshot|null>(null); const [keywords,setKeywords]=useState<KeywordRow[]>([]),[clusters,setClusters]=useState<ClusterRow[]>([]),[tasks,setTasks]=useState<Task[]>([]),[decisions,setDecisions]=useState<Decision[]>([]),[error,setError]=useState('');
 const loadProjects=async()=>{const p=await api<Project[]>('/projects');setProjects(p);if(!projectId&&p[0])setProjectId(p[0].id)};
 const load=async()=>{if(!projectId)return;try{setError('');const [s,k,c,t,d]=await Promise.all([api<Snapshot>(`/projects/${projectId}/snapshot`),api<KeywordRow[]>(`/projects/${projectId}/keywords`),api<ClusterRow[]>(`/projects/${projectId}/clusters`),api<Task[]>(`/projects/${projectId}/tasks`),api<Decision[]>(`/projects/${projectId}/decisions`)]);setSnapshot(s);setKeywords(k);setClusters(c);setTasks(t);setDecisions(d)}catch(e){setError(String(e))}};
 useEffect(()=>{loadProjects().catch(e=>setError(String(e)))},[]); useEffect(()=>{void load()},[projectId]);
 const unclustered=useMemo(()=>keywords.filter(x=>!x.clusterId&&x.keyword.status!=='rejected'),[keywords]);
 async function createProject(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const p=await api<Project>('/projects',{method:'POST',body:JSON.stringify({name:f.get('name'),domain:f.get('domain')})});e.currentTarget.reset();await loadProjects();setProjectId(p.id)}
 async function addKeyword(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api(`/projects/${projectId}/keywords`,{method:'POST',body:JSON.stringify({text:f.get('keyword')})});e.currentTarget.reset();await load()}
 async function addTask(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api(`/projects/${projectId}/tasks`,{method:'POST',body:JSON.stringify({title:f.get('task')})});e.currentTarget.reset();await load()}
 return <div className="app"><aside><div className="brand"><span className="dot"/>KEYWORDS</div><h4>Projects</h4>{projects.map(p=><button className={p.id===projectId?'project active':'project'} onClick={()=>setProjectId(p.id)} key={p.id}><b>{p.name}</b><small>{p.domain||'no domain'}</small></button>)}<form className="stack" onSubmit={createProject}><input name="name" placeholder="New project" required/><input name="domain" placeholder="domain (optional)"/><button>Create project</button></form></aside>
 <main>{error&&<div className="error">{error}</div>}{!snapshot?<section className="empty"><h1>Create a project</h1><p>The workspace state will be shared by the UI, CLI, and MCP agents.</p></section>:<>
 <header><div><p className="eyebrow">SEO WORKSPACE</p><h1>{snapshot.project.name}</h1><p>{snapshot.project.domain||'No domain configured'}</p></div><div className="agent"><span className="pulse"/>Agent-ready</div></header>
 <section className="metrics">{Object.entries(snapshot.counts).map(([k,v])=><div className="metric" key={k}><strong>{v}</strong><span>{k.replace(/([A-Z])/g,' $1')}</span></div>)}</section>
 <div className="grid"><section className="panel map"><div className="panelHead"><div><p className="eyebrow">CONTENT MAP</p><h2>Clusters</h2></div><span>{clusters.length} nodes</span></div><div className="clusterCanvas">{clusters.length?clusters.map((c,i)=><div className="cluster" style={{transform:`translate(${(i%3)*26}px, ${(i%2)*14}px)`}} key={c.cluster.id}><b>{c.cluster.title}</b><span>{c.keywordCount} keywords · {c.cluster.intent}</span></div>):<div className="hint">No clusters yet. An agent can create these through MCP.</div>}</div></section>
 <section className="panel"><div className="panelHead"><div><p className="eyebrow">BACKLOG</p><h2>Unclustered queries</h2></div><span>{unclustered.length}</span></div><form className="inline" onSubmit={addKeyword}><input name="keyword" placeholder="Add keyword" required/><button>+</button></form><div className="list">{unclustered.slice(0,12).map(x=><div className="row" key={x.keyword.id}><div><b>{x.keyword.text}</b><small>{x.keyword.source}</small></div><span>{x.keyword.avgMonthly??'—'}</span></div>)}</div></section>
 <section className="panel"><div className="panelHead"><div><p className="eyebrow">SHARED QUEUE</p><h2>Tasks</h2></div><span>{tasks.filter(t=>t.status!=='done').length} open</span></div><form className="inline" onSubmit={addTask}><input name="task" placeholder="Create a task" required/><button>+</button></form><div className="list">{tasks.slice(0,10).map(t=><div className="task" key={t.id}><span className={`status ${t.status}`}>{t.status}</span><div><b>{t.title}</b><small>{t.assigneeType} · p{t.priority}</small></div></div>)}</div></section>
 <section className="panel activity"><div className="panelHead"><div><p className="eyebrow">AGENT ACTIVITY</p><h2>Command log</h2></div></div><div className="timeline">{snapshot.recentRuns.map(r=><div className="event" key={r.id}><span className={r.status==='succeeded'?'ok':'bad'}/><div><b>{r.command}</b><small>{r.actor} · {new Date(r.createdAt).toLocaleString()} · {r.durationMs??0}ms</small></div></div>)}</div></section>
 <section className="panel decisions"><div className="panelHead"><div><p className="eyebrow">FEEDBACK MEMORY</p><h2>Decisions</h2></div><span>{decisions.length}</span></div>{decisions.slice(0,8).map(d=><div className="decision" key={d.id}><b>{d.verdict}</b><span>{d.action} · {d.targetType}</span><p>{d.reason||'No reason recorded'}</p></div>)}</section></div></>}</main></div>
}
