import { useEffect, useMemo, useState } from 'react';
import { api } from './api';

type Project={id:string;name:string;domain?:string|null};
type Outcome={status:string;publishedAt?:string|null;evaluationDueAt?:string|null;metrics?:Record<string,unknown>;nextAction?:string|null;updatedAt:string}|null;
type Article={id:string;operationId:string;projectId:string;projectName:string;projectDomain?:string|null;pageId?:string|null;articleId:string;title:string;url?:string|null;path:string;contentSha256:string;validatorStatus:string;buildStatus:string;verifiedAt?:string|null;revisionCount:number;failedChecks:string[];updatedAt:string;keyword:{id:string;text:string;avgMonthly?:number|null;clicks?:number|null;impressions?:number|null;position?:number|null;selectionReason?:string|null}|null;outcome:Outcome};
type Result={generatedAt:string;total:number;limit:number;offset:number;items:Article[]};
const pageSize=50;
const when=(value?:string|null)=>value?new Date(value).toLocaleString('ja-JP',{year:'numeric',month:'numeric',day:'numeric'}):'—';
const outcomeLabel:Record<string,string>={pending:'評価待ち',improved:'改善',regressed:'悪化',inconclusive:'未判定',unmeasurable:'計測不能'};

export function ArticlesOverview(){
 const [projects,setProjects]=useState<Project[]>([]),[data,setData]=useState<Result|null>(null),[query,setQuery]=useState(''),[projectId,setProjectId]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{api<Project[]>('/projects').then(setProjects).catch(e=>setError(String(e)))},[]);
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(async()=>{try{setLoading(true);const params=new URLSearchParams({limit:String(pageSize),offset:String(page*pageSize)});if(query.trim())params.set('q',query.trim());if(projectId)params.set('projectId',projectId);if(status!=='all')params.set('status',status);const result=await api<Result>(`/articles?${params}`,{signal:controller.signal});setData(result);setError('')}catch(e){if(!controller.signal.aborted)setError(String(e))}finally{if(!controller.signal.aborted)setLoading(false)}},180);return()=>{clearTimeout(timer);controller.abort()}},[query,projectId,status,page]);
 useEffect(()=>setPage(0),[query,projectId,status]);
 const pages=Math.max(1,Math.ceil((data?.total??0)/pageSize));
 const summary=useMemo(()=>({verified:data?.items.filter(a=>a.verifiedAt).length??0,working:data?.items.filter(a=>!a.verifiedAt).length??0,published:data?.items.filter(a=>a.outcome?.publishedAt).length??0,regressed:data?.items.filter(a=>a.outcome?.status==='regressed').length??0}),[data]);
 return <div className="corePage">
  <div className="coreTitleRow"><div><p className="coreEyebrow">ARTICLE INDEX</p><h1>記事</h1><p>大量の記事を検索・絞り込みし、必要な行だけ詳細を開きます。</p></div><span className="countBadge">{data?.total??0} articles</span></div>
  {error&&<div className="coreError">{error}</div>}
  <div className="articleSummary"><span><b>{summary.verified}</b> このページで検証済み</span><span><b>{summary.working}</b> 制作中</span><span><b>{summary.published}</b> 公開済み</span><span className={summary.regressed?'dangerMetric':''}><b>{summary.regressed}</b> 悪化</span></div>
  <div className="coreToolbar articleToolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="記事名・キーワード・サイトを検索"/><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">すべてのサイト</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="segmented"><button className={status==='all'?'active':''} onClick={()=>setStatus('all')}>すべて</button><button className={status==='in_progress'?'active':''} onClick={()=>setStatus('in_progress')}>制作中</button><button className={status==='complete'?'active':''} onClick={()=>setStatus('complete')}>検証済み</button></div></div>
  <div className="articleTableWrap"><table className="articleTable"><thead><tr><th>記事</th><th>サイト</th><th>キーワード</th><th>状態</th><th>公開後</th><th>更新</th></tr></thead><tbody>{!loading&&data?.items.map(a=><tr key={a.id}><td colSpan={6}><details className="articleDetail"><summary><span className="articleCellTitle"><b>{a.title}</b><small>{a.path}</small></span><span>{a.projectName}</span><span>{a.keyword?.text||'—'}</span><span><i className={`statusPill ${a.verifiedAt?'good':'work'}`}>{a.verifiedAt?'検証済み':'制作中'}</i></span><span><i className={`statusPill ${a.outcome?.status||'neutral'}`}>{a.outcome?.publishedAt?(outcomeLabel[a.outcome.status]||'公開済み'):'未公開'}</i></span><span>{when(a.updatedAt)}</span></summary><div className="articleExpanded"><div><h3>キーワード選定</h3><p><b>{a.keyword?.text||'紐づくメインキーワードなし'}</b>{a.keyword?.avgMonthly!=null?` · 月間 ${a.keyword.avgMonthly}`:''}{a.keyword?.position!=null?` · 順位 ${Number(a.keyword.position).toFixed(1)}`:''}</p><small>{a.keyword?.selectionReason||'選定理由の記録なし'}</small></div><div><h3>制作・検証</h3><p>validator {a.validatorStatus} / build {a.buildStatus} / revision {a.revisionCount}</p>{a.failedChecks.length?<small className="badText">未通過: {a.failedChecks.join(' / ')}</small>:<small>SHA {a.contentSha256.slice(0,16)}…</small>}</div><div><h3>公開後評価</h3>{a.outcome?<><p>{outcomeLabel[a.outcome.status]||a.outcome.status}{a.outcome.publishedAt?` · 公開 ${when(a.outcome.publishedAt)}`:''}</p><small>{a.outcome.nextAction||`評価予定 ${when(a.outcome.evaluationDueAt)}`}</small>{a.outcome.metrics&&Object.keys(a.outcome.metrics).length?<code>{Object.entries(a.outcome.metrics).slice(0,6).map(([k,v])=>`${k}: ${String(v)}`).join(' · ')}</code>:null}</>:<p>まだ公開後評価はありません。</p>}</div></div></details></td></tr>)}{loading&&<tr><td colSpan={6}><div className="tableLoading">読み込み中…</div></td></tr>}{!loading&&data?.items.length===0&&<tr><td colSpan={6}><div className="coreEmpty">条件に一致する記事はありません。</div></td></tr>}</tbody></table></div>
  <div className="pagination"><button disabled={page===0} onClick={()=>setPage(p=>Math.max(0,p-1))}>← 前へ</button><span>{page+1} / {pages}</span><button disabled={page+1>=pages} onClick={()=>setPage(p=>p+1)}>次へ →</button></div>
 </div>;
}
