import { FormEvent, useEffect, useState } from 'react';
import { api } from './api';
import type { Capability, DiscoveryCandidate, DiscoveryDetail, DiscoveryJob, ProjectBrief } from './product-types';

const when=(value:string|null)=>value?new Date(value).toLocaleString():'—';
const labels:Record<string,string>={waiting_for_agent:'Agent待ち',running:'調査中',awaiting_review:'確認待ち',completed:'完了',blocked:'停止中',failed:'失敗',cancelled:'取消',discovered:'未確認',shortlisted:'候補入り',hold:'保留',rejected:'除外',research_more:'追加調査'};

export function DiscoveryWorkspace({projectId,onChanged}:{projectId:string;onChanged:()=>void}){
 const [brief,setBrief]=useState<ProjectBrief|null>(null),[capabilities,setCapabilities]=useState<Capability[]>([]),[jobs,setJobs]=useState<DiscoveryJob[]>([]),[detail,setDetail]=useState<DiscoveryDetail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const load=async()=>{try{const [b,c,j]=await Promise.all([api<ProjectBrief>(`/projects/${projectId}/brief`),api<Capability[]>(`/projects/${projectId}/capabilities`),api<DiscoveryJob[]>(`/projects/${projectId}/discovery-jobs`)]);setBrief(b);setCapabilities(c);setJobs(j);const selected=detail?.job.id&&j.some(x=>x.id===detail.job.id)?detail.job.id:j[0]?.id;if(selected)setDetail(await api<DiscoveryDetail>(`/projects/${projectId}/discovery-jobs/${selected}`));else setDetail(null);setError('')}catch(e){setError(String(e))}};
 useEffect(()=>{void load()},[projectId]);
 async function start(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);try{setBusy('start');setError('');await api(`/projects/${projectId}/discovery-jobs`,{method:'POST',body:JSON.stringify({seedKeywords:String(f.get('seeds')||'').split(',').map(x=>x.trim()).filter(Boolean),targetUrl:String(f.get('url')||'')||undefined,goal:f.get('goal'),language:f.get('language'),country:f.get('country'),region:f.get('region')||undefined,excludedTerms:String(f.get('exclude')||'').split(',').map(x=>x.trim()).filter(Boolean),maxCandidates:Number(f.get('maxCandidates')),maxExternalRequests:Number(f.get('maxRequests'))})});form.reset();await load();onChanged()}catch(e){setError(String(e))}finally{setBusy('')}}
 async function open(jobId:string){try{setDetail(await api<DiscoveryDetail>(`/projects/${projectId}/discovery-jobs/${jobId}`))}catch(e){setError(String(e))}}
 async function review(c:DiscoveryCandidate,status:'shortlisted'|'hold'|'rejected'|'research_more'){try{setBusy(c.id+status);await api(`/projects/${projectId}/discovery-jobs/${c.jobId}/candidates/${c.id}/review`,{method:'POST',body:JSON.stringify({status})});setDetail(await api<DiscoveryDetail>(`/projects/${projectId}/discovery-jobs/${c.jobId}`));await load();onChanged()}catch(e){setError(String(e))}finally{setBusy('')}}
 if(!brief)return <section className="panel"><div className="hint">探索設定を読み込み中…</div></section>;
 const unavailable=capabilities.filter(c=>c.status!=='available');
 return <div className="productStack">
  {error&&<div className="error">{error}</div>}
  <section className="panel discoveryHero"><div className="panelHead"><div><p className="eyebrow">DISCOVERY</p><h2>新しいキーワードを探す</h2></div><span>{brief.language.toUpperCase()} · {brief.country.toUpperCase()}</span></div>
   <p className="lead">目的と上限を渡すと、Agent が共有コマンドで必要な調査だけを行います。候補は自動採用されません。</p>
   <form className="formGrid" onSubmit={start}>
    <label><span>シード語（カンマ区切り）</span><input name="seeds" placeholder={brief.topic||'例: SEO 自動化, キーワード調査'}/></label>
    <label><span>対象URL（任意）</span><input name="url" type="url" placeholder={brief.domain?`https://${brief.domain}`:'https://example.com'}/></label>
    <label className="span2"><span>探索目的</span><input name="goal" required placeholder="例: 個人サイトで狙える新規記事テーマを見つける"/></label>
    <label><span>言語</span><input name="language" defaultValue={brief.language} required/></label><label><span>国</span><input name="country" defaultValue={brief.country} required/></label>
    <label><span>地域（任意）</span><input name="region" defaultValue={brief.region||''}/></label><label><span>除外語</span><input name="exclude" defaultValue={brief.excludedTerms.join(', ')}/></label>
    <label><span>候補上限</span><input name="maxCandidates" type="number" min="1" max="500" defaultValue={brief.discoveryMaxCandidates}/></label><label><span>外部調査上限</span><input name="maxRequests" type="number" min="1" max="50" defaultValue={brief.discoveryMaxExternalRequests}/></label>
    <div className="span2 actionLine"><button className="primaryAction" disabled={busy==='start'}>{busy==='start'?'作成中…':'探索をAgentに依頼'}</button><small>開始後は「Agent待ち」→「調査中」→「確認待ち」と進みます。</small></div>
   </form>
   <div className="capabilityStrip">{capabilities.map(c=><span className={`cap ${c.status}`} title={c.reason||''} key={c.provider}>{c.provider}: {c.status==='available'?'利用可':c.status}</span>)}</div>
   {unavailable.length>0&&<div className="hint">未設定のProviderがあっても、利用可能な手段だけで作業できます。理由は設定画面で確認できます。</div>}
  </section>
  <div className="twoColumn">
   <section className="panel"><div className="panelHead"><div><p className="eyebrow">JOBS</p><h2>探索履歴</h2></div><span>{jobs.length}</span></div><div className="list">{jobs.map(j=><button className={`jobRow ${detail?.job.id===j.id?'selected':''}`} key={j.id} onClick={()=>void open(j.id)}><div><b>{j.goal}</b><small>{when(j.createdAt)} · {j.externalRequestsUsed}/{j.maxExternalRequests} external requests</small></div><span className={`status ${j.status}`}>{labels[j.status]||j.status}</span></button>)}{!jobs.length&&<div className="hint">まだ探索履歴はありません。</div>}</div></section>
   <section className="panel"><div className="panelHead"><div><p className="eyebrow">CURRENT STATE</p><h2>{detail?.job.goal||'探索を選択'}</h2></div>{detail&&<span className={`status ${detail.job.status}`}>{labels[detail.job.status]||detail.job.status}</span>}</div>{detail&&<><div className="budgetBox"><b>外部調査 {detail.job.externalRequestsUsed}/{detail.job.maxExternalRequests}</b><div className="workMeter"><span style={{width:`${Math.min(100,detail.job.externalRequestsUsed/Math.max(1,detail.job.maxExternalRequests)*100)}%`}}/></div><small>これは進捗率ではなく、許可した外部リクエスト上限の消費量です。</small></div><p>{detail.job.status==='waiting_for_agent'?'Agentが接続してclaimするまで実行中にはなりません。':detail.job.status==='awaiting_review'?'調査が終わりました。候補を人間が選別してください。':'状態は共有DBに保存され、再起動後も再開できます。'}</p></>}</section>
  </div>
  {detail&&<section className="panel"><div className="panelHead"><div><p className="eyebrow">CANDIDATE REVIEW</p><h2>候補を比較する</h2></div><span>{detail.candidates.length}</span></div><div className="candidateTable"><div className="candidateHeader"><span>キーワード</span><span>需要</span><span>調査</span><span>判断</span></div>{detail.candidates.map(c=><div className="candidateRow" key={c.id}><div><b>{c.keyword}</b><small>{c.searchIntent||'検索意図: 未確認'}</small><small>{c.existingPageOverlap?.length?`既存ページ重複 ${c.existingPageOverlap.length}件`:'既存ページ重複なし/未検出'}</small>{c.unresolvedQuestions.length>0&&<small>未確認: {c.unresolvedQuestions.join(' / ')}</small>}</div><div><b>{c.demandValue??'未取得'}</b><small>{c.demandProvider||'providerなし'} · {when(c.demandObservedAt)}</small>{c.adCompetition!==null&&<small>広告競合度 {Math.round(c.adCompetition*100)}%</small>}</div><div><b>{c.evidenceCount} evidence</b><small>SERP: {c.serpStatus}</small><small>{c.language}/{c.country}{c.region?` · ${c.region}`:''}</small></div><div><span className={`status ${c.status}`}>{labels[c.status]||c.status}</span>{detail.job.status==='awaiting_review'||detail.job.status==='completed'||detail.job.status==='waiting_for_agent'?<div className="reviewButtons"><button disabled={!!busy} onClick={()=>void review(c,'shortlisted')}>候補入り</button><button disabled={!!busy} onClick={()=>void review(c,'hold')}>保留</button><button disabled={!!busy} onClick={()=>void review(c,'research_more')}>追加調査</button><button disabled={!!busy} onClick={()=>void review(c,'rejected')}>除外</button></div>:<small>Agent調査中</small>}</div></div>)}</div></section>}
 </div>;
}
