import { useEffect, useMemo, useState } from 'react';
import { api } from './api';

type Item = { id:string; keyword:string; seed?:string; status?:string; volume?:number|null; competition?:string|number|null; allintitle?:number|null; serpWeakness?:number|null; notes?:string; updatedAt:string };
const label:Record<string,string>={inbox:'受信箱',shortlisted:'有望',rejected:'見送り',published:'公開済み'};

export function KeywordTreasury(){
  const [items,setItems]=useState<Item[]>([]); const [status,setStatus]=useState(''); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');try{setItems(await api<Item[]>(`/keyword-treasury?${new URLSearchParams(Object.fromEntries(Object.entries({status,query}).filter(([,value])=>value))).toString()}`))}catch(e){setError(e instanceof Error?e.message:'共有ストックを取得できませんでした')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[status]);
  const visible=useMemo(()=>items.filter(item=>!query||`${item.keyword} ${item.seed??''} ${item.notes??''}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  return <section className="treasuryView"><div className="coreSectionHead"><div><p className="coreEyebrow">SHARED FIRESTORE TREASURY</p><h1>お宝キーワード</h1><p>リモートMCPで保存した候補を、ローカルから確認します。</p></div><button onClick={()=>void load()} disabled={loading}>更新</button></div><div className="coreToolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="キーワード・シード・メモを検索" aria-label="お宝キーワードを検索"/><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="状態で絞り込み"><option value="">すべての状態</option>{Object.entries(label).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select><span>{visible.length}件</span></div>{error?<div className="systemNotice"><div><strong>共有ストックに接続できません</strong><p>{error}</p><small>ローカルの .env に Firestore の読み取り用サービスアカウント設定が必要です。</small></div></div>:loading?<div className="dashboardSkeleton" aria-label="お宝キーワードを読み込み中"><span/><span/><span/></div>:<div className="treasuryTable" role="region" aria-label="お宝キーワード一覧"><table><thead><tr><th>キーワード</th><th>状態</th><th>需要</th><th>競合シグナル</th><th>根拠・メモ</th><th>更新</th></tr></thead><tbody>{visible.map(item=><tr key={item.id}><td><b>{item.keyword}</b>{item.seed&&<small>seed: {item.seed}</small>}</td><td><span className={`statusPill ${item.status??'inbox'}`}>{label[item.status??'inbox']??item.status}</span></td><td>{item.volume??'—'}{item.competition!=null&&<small>{String(item.competition)}</small>}</td><td><span>allintitle {item.allintitle??'—'}</span><small>SERP弱さ {item.serpWeakness??'—'}</small></td><td>{item.notes||'—'}</td><td>{item.updatedAt?new Intl.DateTimeFormat('ja-JP',{dateStyle:'short',timeStyle:'short'}).format(new Date(item.updatedAt)):'—'}</td></tr>)}</tbody></table>{!visible.length&&<p className="coreEmpty">保存済みの候補はありません。</p>}</div>}</section>
}
