import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api } from './api';

type Delegation={id:string;capability:string;status:string;limits:Record<string,unknown>;expiresAt?:string|null};
type Review={id:string;title:string;question?:string|null;created_at?:string;createdAt?:string};
type Event={id:string;kind:string;severity:string;payload:Record<string,unknown>;createdAt:string};
type Outcome={id:string;status:string;targetUrl?:string|null;hypothesis?:string|null;metrics:Record<string,unknown>;nextAction?:string|null;updatedAt:string};
type Work={id:string;objective:string;status:string;summary?:string|null;nextAction?:string|null;updatedAt:string};
type Executor={id:string;status:string;connected:boolean;lastSeenAt:string;leaseExpiresAt?:string|null;generation:number}|null;
type OperationProject={projectId:string;name:string;status:string;workSessionId?:string|null;taskId?:string|null;work?:{objective:string;status:string;summary?:string|null;nextAction?:string|null}|null};
type Operation={id:string;objective:string;requestText:string;status:string;updatedAt:string;projects:OperationProject[];events:Event[];outcomes:Outcome[]};
type Context={review:Review|null;reviews:Review[];work:Work|null;executor:Executor;latestOutcome:Outcome|null;control:{paused:boolean;reason?:string|null};activeOperation:Operation|null;recentEvents:Event[];delegations:Delegation[]};
type Operator={next:{kind:string;title?:string;reason?:string};candidates:Array<{kind:string;title?:string;reason?:string;rank:number}>};

const capabilities=[
 ['operation.start','運用依頼の開始'],['discovery.start','キーワード探索の開始'],['measurement.capture','検索実績の取得'],['site.sync','サイト同期'],
 ['candidate.triage','候補の定型仕分け'],['blog.transport','承認済みBlog handoffの受け渡し'],['outcome.record','成果観測の記録']
] as const;
const when=(value?:string|null)=>value?new Date(value).toLocaleString():'—';

export function OperationsHome({projectId,onChanged}:{projectId:string;onChanged:()=>void}){
 const [context,setContext]=useState<Context|null>(null),[operator,setOperator]=useState<Operator|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[request,setRequest]=useState('');
 const activeDelegations=useMemo(()=>new Map((context?.delegations??[]).filter(d=>d.status==='active').map(d=>[d.capability,d])),[context]);
 const load=async()=>{try{const [c,o]=await Promise.all([api<Context>(`/operations/context?projectId=${encodeURIComponent(projectId)}`),api<Operator>(`/projects/${projectId}/operator`)]);setContext(c);setOperator(o);setError('')}catch(e){setError(String(e))}};
 useEffect(()=>{void load()},[projectId]);
 async function start(e:FormEvent){e.preventDefault();const text=request.trim();if(!text)return;try{setBusy('start');await api('/operations',{method:'POST',body:JSON.stringify({requestText:text,projectIds:[projectId],conversationRef:`web:${projectId}`,budget:{maxActions:16,maxExternalRequests:10,maxCandidateWrites:80,maxProjects:1,maxRuntimeMinutes:45}})});setRequest('');await load();onChanged()}catch(e){setError(String(e))}finally{setBusy('')}}
 async function setPause(paused:boolean){try{setBusy('pause');await api(`/operations/projects/${projectId}/pause`,{method:'POST',body:JSON.stringify({paused,reason:paused?'Paused from Today operations UI':undefined})});await load()}catch(e){setError(String(e))}finally{setBusy('')}}
 async function grant(capability:string){try{setBusy(capability);const defaultLimits=capability==='candidate.triage'?{allowedStatuses:['hold','rejected','research_more'],maxBatch:50}:capability==='measurement.capture'?{maxRows:25000}:{};await api(`/operations/projects/${projectId}/delegations`,{method:'POST',body:JSON.stringify({capability,limits:defaultLimits})});await load()}catch(e){setError(String(e))}finally{setBusy('')}}
 async function revoke(delegation:Delegation){try{setBusy(delegation.capability);await api(`/operations/projects/${projectId}/delegations/${delegation.id}/revoke`,{method:'POST',body:JSON.stringify({reason:'Revoked from Today operations UI'})});await load()}catch(e){setError(String(e))}finally{setBusy('')}}
 const reviews=context?.reviews??[];
 return <div className="productStack">{error&&<div className="error">{error}</div>}
  <section className="homeHero"><div><p className="eyebrow">TODAY / OPERATIONS</p><h2>やりたいことを渡して、判断だけ返す</h2><p>依頼は共有Operationに変換され、Agentは委任・予算・pause・公開境界を越えずに進めます。</p></div><div className="stack"><span className="sourceType">Agent {context?.executor?.connected?'接続中':'未接続'}{context?.executor?` · ${context.executor.id}`:''}</span><button onClick={()=>void setPause(!context?.control.paused)} disabled={busy==='pause'}>{context?.control.paused?'Agentを再開':'Agentを一時停止'}</button></div></section>
  <form className="panel stack" onSubmit={start}><div className="panelHead"><div><p className="eyebrow">REQUEST</p><h2>運用を依頼</h2></div>{context?.activeOperation&&<span>{context.activeOperation.status}</span>}</div><textarea value={request} onChange={e=>setRequest(e.target.value)} placeholder="例: このサイトで今やる価値が高いSEO改善を1件、根拠を集めて提案まで進めて。公開はしないで。" rows={3}/><div className="row"><button className="primaryAction" disabled={busy==='start'||!request.trim()}>{busy==='start'?'開始中…':'Agentに渡す'}</button>{context?.control.paused&&<small>現在pause中です。依頼は作成できますがAgent実行は再開後です。</small>}</div></form>

  <div className="twoColumn"><section className="panel"><div className="panelHead"><div><p className="eyebrow">JUDGMENT REQUIRED</p><h2>判断が必要</h2></div><span>{reviews.length}</span></div><div className="list">{reviews.map(r=><div className="task" key={r.id}><span className="status review">review</span><div><b>{r.title}</b>{r.question&&<small>{r.question}</small>}<small>{when(r.created_at??r.createdAt)}</small></div></div>)}{!reviews.length&&<div className="hint">今すぐ必要な人間判断はありません。</div>}</div></section>
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">IN PROGRESS</p><h2>進行中の作業</h2></div></div>{context?.activeOperation?<div className="list"><div className="task"><span className={`status ${context.activeOperation.status}`}>{context.activeOperation.status}</span><div><b>{context.activeOperation.objective}</b><small>Operation {context.activeOperation.id}</small></div></div>{context.activeOperation.projects.map(p=><div className="task" key={p.projectId}><span className={`status ${p.work?.status??p.status}`}>{p.work?.status??p.status}</span><div><b>{p.name}</b><small>{p.work?.summary||p.work?.nextAction||p.work?.objective||'共有work sessionに接続済み'}</small></div></div>)}</div>:context?.work?<div className="task"><span className={`status ${context.work.status}`}>{context.work.status}</span><div><b>{context.work.objective}</b><small>{context.work.summary||context.work.nextAction||when(context.work.updatedAt)}</small></div></div>:<div className="hint">進行中のOperationはありません。</div>}</section></div>

  <div className="twoColumn"><section className="panel"><div className="panelHead"><div><p className="eyebrow">RESULTS</p><h2>完了・観測したこと</h2></div></div><div className="list">{(context?.activeOperation?.outcomes??(context?.latestOutcome?[context.latestOutcome]:[])).slice(0,6).map(o=><div className="task" key={o.id}><span className={`status ${o.status}`}>{o.status}</span><div><b>{o.hypothesis||o.targetUrl||'Operation outcome'}</b><small>{o.nextAction||`更新 ${when(o.updatedAt)}`}</small></div></div>)}{context?.recentEvents?.filter(e=>['operation_completed','meaningful_outcome','major_failure'].includes(e.kind)).slice(0,5).map(e=><div className="event" key={e.id}><span className={e.severity==='error'?'bad':'ok'}/><div><b>{e.kind}</b><small>{when(e.createdAt)}</small></div></div>)}{!context?.latestOutcome&&!context?.recentEvents?.length&&<div className="hint">成果観測はまだありません。</div>}</div></section>
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">NEXT CANDIDATES</p><h2>次候補</h2></div></div><div className="list">{operator?.candidates.slice(0,6).map(c=><div className="task" key={`${c.rank}-${c.kind}`}><span className="sourceType">{c.kind}</span><div><b>{c.title||c.kind}</b><small>{c.reason}</small></div></div>)}{!operator?.candidates.length&&<div className="hint">現時点で根拠のある次アクションはありません。</div>}</div></section></div>

  <section className="panel"><div className="panelHead"><div><p className="eyebrow">DELEGATION</p><h2>Agentに任せる範囲</h2></div><span>{activeDelegations.size}/{capabilities.length}</span></div><div className="list">{capabilities.map(([capability,label])=>{const active=activeDelegations.get(capability);return <div className="governanceRow" key={capability}><div><b>{label}</b><small>{capability}{active?` · version ${active.id.slice(0,8)}`:' · 未委任'}</small></div><button disabled={!!busy} onClick={()=>void(active?revoke(active):grant(capability))}>{active?'取り消す':'委任する'}</button></div>})}</div><div className="hint">公開・削除・policy有効化・レビュー解決はこの委任一覧に含まれず、人間境界のままです。</div></section>
 </div>;
}
