import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api } from './api';
import type { ClusterRow, KeywordSearchResult, PageRow } from './product-types';

type Source={id:string;type:string;label:string;url:string|null;createdAt:string};
export function PlanningWorkspace({projectId,onChanged}:{projectId:string;onChanged:()=>void}){
 const [clusters,setClusters]=useState<ClusterRow[]>([]),[shortlist,setShortlist]=useState<KeywordSearchResult|null>(null),[pages,setPages]=useState<PageRow[]>([]),[sources,setSources]=useState<Source[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[reason,setReason]=useState<Record<string,string>>({});
 const load=async()=>{try{const [c,k,p,s]=await Promise.all([api<ClusterRow[]>(`/projects/${projectId}/clusters`),api<KeywordSearchResult>(`/projects/${projectId}/keywords/search?candidateStatus=shortlisted&limit=200&offset=0`),api<PageRow[]>(`/projects/${projectId}/pages`),api<Source[]>(`/projects/${projectId}/sources`)]);setClusters(c);setShortlist(k);setPages(p);setSources(s);setError('')}catch(e){setError(String(e))}};
 useEffect(()=>{void load()},[projectId]);
 async function createCluster(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{setBusy('cluster');const c=await api<{id:string}>(`/projects/${projectId}/clusters`,{method:'POST',body:JSON.stringify({title:f.get('title'),intent:f.get('intent')})});const ids=String(f.get('keywords')||'').split(',').filter(Boolean);if(ids.length)await api(`/projects/${projectId}/clusters/${c.id}/keywords`,{method:'POST',body:JSON.stringify({keywordIds:ids})});e.currentTarget.reset();await load();onChanged()}catch(e){setError(String(e))}finally{setBusy('')}}
 async function plan(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);try{setBusy('plan');const secondary=String(f.get('secondary')||'').split(',').filter(Boolean);const sourceIds=String(f.get('sources')||'').split(',').filter(Boolean);await api(`/projects/${projectId}/pages/plan`,{method:'POST',body:JSON.stringify({title:f.get('title'),clusterId:f.get('cluster')||undefined,primaryKeywordId:f.get('primary')||undefined,secondaryKeywordIds:secondary,sourceIds,audience:f.get('audience'),question:f.get('question'),searchIntent:f.get('intent'),uniqueAngle:f.get('angle'),unresolvedAssumptions:String(f.get('assumptions')||'').split('\n').map(x=>x.trim()).filter(Boolean),rationale:f.get('rationale'),planMode:f.get('planMode'),targetPageId:f.get('targetPage')||undefined})});form.reset();await load();onChanged()}catch(e){setError(String(e))}finally{setBusy('')}}
 async function review(pageId:string,verdict:'approved'|'needs_edit'|'rejected'){const why=(reason[pageId]||'').trim();if(verdict!=='approved'&&!why){setError('修正依頼・却下には理由を入力してください。');return}try{setBusy(pageId+verdict);await api(`/projects/${projectId}/pages/${pageId}/review`,{method:'POST',body:JSON.stringify({verdict,reason:why||undefined})});setReason(v=>({...v,[pageId]:''}));await load();onChanged()}catch(e){setError(String(e))}finally{setBusy('')}}
 const livePages=useMemo(()=>pages.filter(p=>p.url&&['published','stale'].includes(p.status)),[pages]);
 const proposed=pages.filter(p=>p.status==='proposed');
 return <div className="productStack">{error&&<div className="error">{error}</div>}
  <div className="twoColumn"><section className="panel"><div className="panelHead"><div><p className="eyebrow">SHORTLIST → CLUSTER</p><h2>候補を構造化する</h2></div><span>{shortlist?.total??0} shortlisted</span></div><form className="formGrid" onSubmit={createCluster}><label className="span2"><span>クラスタ名</span><input name="title" required placeholder="例: AI SEO ワークフロー"/></label><label><span>検索意図</span><select name="intent"><option value="informational">情報収集</option><option value="commercial">比較・検討</option><option value="transactional">行動</option><option value="mixed">混合</option></select></label><label><span>含める候補</span><select name="keywords" multiple size={5}>{shortlist?.items.map(r=><option key={r.keyword.id} value={r.keyword.id}>{r.keyword.text}</option>)}</select></label><button className="primaryAction span2" disabled={busy==='cluster'}>{busy==='cluster'?'作成中…':'クラスタを作成'}</button></form></section>
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">CLUSTERS</p><h2>コンテンツ構造</h2></div><span>{clusters.length}</span></div><div className="list">{clusters.map(c=><div className="row" key={c.cluster.id}><div><b>{c.cluster.title}</b><small>{c.cluster.intent}</small></div><span>{c.keywordCount}語</span></div>)}{!clusters.length&&<div className="hint">クラスタはまだありません。</div>}</div></section></div>
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">PAGE PLAN</p><h2>根拠付き企画を作る</h2></div><span>公開処理は行いません</span></div><form className="formGrid" onSubmit={plan}><label className="span2"><span>企画タイトル</span><input name="title" required/></label><label><span>クラスタ</span><select name="cluster"><option value="">未指定</option>{clusters.map(c=><option value={c.cluster.id} key={c.cluster.id}>{c.cluster.title}</option>)}</select></label><label><span>企画種別</span><select name="planMode"><option value="new_page">新規ページ</option><option value="existing_page_improvement">既存ページ改善</option></select></label><label><span>改善対象（既存ページの場合）</span><select name="targetPage"><option value="">なし</option>{livePages.map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label><label><span>主キーワード</span><select name="primary"><option value="">未指定</option>{shortlist?.items.map(r=><option value={r.keyword.id} key={r.keyword.id}>{r.keyword.text}</option>)}</select></label><label><span>副キーワード</span><select name="secondary" multiple size={4}>{shortlist?.items.map(r=><option value={r.keyword.id} key={r.keyword.id}>{r.keyword.text}</option>)}</select></label><label><span>対象読者</span><input name="audience" required/></label><label><span>解決する問い</span><input name="question" required/></label><label><span>検索意図</span><input name="intent" required/></label><label><span>独自情報・角度</span><input name="angle" required/></label><label className="span2"><span>根拠ソース</span><select name="sources" multiple size={4}>{sources.slice(0,100).map(s=><option value={s.id} key={s.id}>{s.type} · {s.label}</option>)}</select></label><label className="span2"><span>未確認事項（1行1件）</span><textarea name="assumptions" rows={3}/></label><label className="span2"><span>企画理由</span><textarea name="rationale" rows={3} required/></label><button className="primaryAction span2" disabled={busy==='plan'}>{busy==='plan'?'保存中…':'企画をHuman Reviewへ'}</button></form></section>
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">HUMAN REVIEW</p><h2>企画レビュー</h2></div><span>{proposed.length}件</span></div><div className="list">{proposed.map(p=><div className="reviewPlan" key={p.id}><div className="reviewPlanBody"><span className={`status ${p.status}`}>{p.planMode==='existing_page_improvement'?'既存改善':'新規'}</span><b>{p.title}</b><small>{p.audience||'読者未設定'} · {p.searchIntent||'検索意図未設定'}</small>{p.question&&<p>{p.question}</p>}{p.uniqueAngle&&<small>独自角度: {p.uniqueAngle}</small>}{p.rationale&&<small>理由: {p.rationale}</small>}</div><div className="reviewPlanActions"><textarea value={reason[p.id]||''} onChange={e=>setReason(v=>({...v,[p.id]:e.target.value}))} placeholder="修正・却下理由" rows={2}/><div><button disabled={!!busy} onClick={()=>void review(p.id,'approved')}>承認</button><button disabled={!!busy} onClick={()=>void review(p.id,'needs_edit')}>修正依頼</button><button disabled={!!busy} onClick={()=>void review(p.id,'rejected')}>却下</button></div></div></div>)}{!proposed.length&&<div className="hint">確認待ちの企画はありません。</div>}</div></section>
 </div>;
}
