import { FormEvent, useEffect, useState } from 'react';
import { api } from './api';
import type { Capability, ProjectBrief } from './product-types';

type Continuous={jobs:number;candidateCounts:Record<string,number>;adoptionRate:number|null;lastJob:any;schedule:{cadenceDays:number;lastDiscoveryAt:string|null;dueAt:string|null;due:boolean}};
type Diagnostics={database:{path:string;journalMode:unknown;foreignKeys:unknown;quickCheck:unknown};runtime:{node:string;cwd:string;platform:string};providers:Record<string,boolean>;counts:Record<string,number>};
export function SettingsWorkspace({projectId,onChanged}:{projectId:string;onChanged:()=>void}){
 const [brief,setBrief]=useState<ProjectBrief|null>(null),[caps,setCaps]=useState<Capability[]>([]),[continuous,setContinuous]=useState<Continuous|null>(null),[diag,setDiag]=useState<Diagnostics|null>(null),[backup,setBackup]=useState<string>(''),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const load=async()=>{try{const [b,c,d]=await Promise.all([api<ProjectBrief>(`/projects/${projectId}/brief`),api<Capability[]>(`/projects/${projectId}/capabilities`),api<Continuous>(`/projects/${projectId}/continuous-discovery`)]);setBrief(b);setCaps(c);setContinuous(d);setError('')}catch(e){setError(String(e))}};
 useEffect(()=>{void load()},[projectId]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{setBusy('save');await api(`/projects/${projectId}/brief`,{method:'PATCH',body:JSON.stringify({mode:f.get('mode'),domain:f.get('domain'),topic:f.get('topic'),audience:f.get('audience'),language:f.get('language'),country:f.get('country'),region:f.get('region'),excludedTerms:String(f.get('excluded')||'').split(',').map(x=>x.trim()).filter(Boolean),discoveryCadenceDays:Number(f.get('cadence')),discoveryMaxCandidates:Number(f.get('maxCandidates')),discoveryMaxExternalRequests:Number(f.get('maxRequests'))})});await load();onChanged()}catch(e){setError(String(e))}finally{setBusy('')}}
 async function diagnostics(){try{setBusy('diag');setDiag(await api<Diagnostics>('/maintenance/diagnostics'))}catch(e){setError(String(e))}finally{setBusy('')}}
 async function createBackup(){try{setBusy('backup');const out=await api<{destination:string}>('/maintenance/backup',{method:'POST',body:'{}'});setBackup(out.destination)}catch(e){setError(String(e))}finally{setBusy('')}}
 if(!brief)return <section className="panel"><div className="hint">設定を読み込み中…</div></section>;
 return <div className="productStack">{error&&<div className="error">{error}</div>}
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">PROJECT BRIEF</p><h2>調査対象と制約</h2></div><span>{brief.mode}</span></div><form className="formGrid" onSubmit={save}><label><span>運用モード</span><select name="mode" defaultValue={brief.mode}><option value="topic_only">テーマから企画</option><option value="existing_site">既存サイト運用</option></select></label><label><span>ドメイン</span><input name="domain" defaultValue={brief.domain||''}/></label><label className="span2"><span>テーマ / 商品 / サービス</span><input name="topic" defaultValue={brief.topic||''}/></label><label className="span2"><span>対象読者</span><input name="audience" defaultValue={brief.audience||''}/></label><label><span>言語</span><input name="language" defaultValue={brief.language} required/></label><label><span>国</span><input name="country" defaultValue={brief.country} required/></label><label><span>地域</span><input name="region" defaultValue={brief.region||''}/></label><label><span>除外テーマ・語</span><input name="excluded" defaultValue={brief.excludedTerms.join(', ')}/></label><label><span>再探索間隔（日）</span><input name="cadence" type="number" min="1" max="365" defaultValue={brief.discoveryCadenceDays}/></label><label><span>1回の候補上限</span><input name="maxCandidates" type="number" min="1" max="500" defaultValue={brief.discoveryMaxCandidates}/></label><label><span>1回の外部調査上限</span><input name="maxRequests" type="number" min="1" max="50" defaultValue={brief.discoveryMaxExternalRequests}/></label><button className="primaryAction span2" disabled={busy==='save'}>{busy==='save'?'保存中…':'Project briefを保存'}</button></form></section>
  <div className="twoColumn"><section className="panel"><div className="panelHead"><div><p className="eyebrow">CAPABILITIES</p><h2>接続状態</h2></div></div><div className="list">{caps.map(c=><div className="row" key={c.provider}><div><b>{c.provider}</b><small>{c.reason||`最終成功: ${c.lastSuccessAt?new Date(c.lastSuccessAt).toLocaleString():'未記録'}`}</small></div><span className={`status ${c.status}`}>{c.status}</span></div>)}</div><div className="hint">認証情報そのものはワークスペースDBへ保存しません。</div></section>
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">CONTINUOUS DISCOVERY</p><h2>探索の振り返り</h2></div><span>{continuous?.schedule.due?'探索時期':'次回待ち'}</span></div>{continuous&&<div className="summaryCards"><div><b>{continuous.jobs}</b><span>探索回数</span></div><div><b>{continuous.candidateCounts.shortlisted??0}</b><span>候補入り</span></div><div><b>{continuous.adoptionRate===null?'—':`${Math.round(continuous.adoptionRate*100)}%`}</b><span>候補入り率</span></div></div>}<small>次回: {continuous?.schedule.dueAt?new Date(continuous.schedule.dueAt).toLocaleString():'未実施'}</small><div className="hint">検索順位の前後差だけで探索効果を断定しません。ここでは採用・保留など運用品質を先に追います。</div></section></div>
  <section className="panel"><div className="panelHead"><div><p className="eyebrow">DATA SAFETY</p><h2>起動・DB診断・バックアップ</h2></div></div><div className="actionLine"><button onClick={()=>void diagnostics()} disabled={busy==='diag'}>診断を実行</button><button onClick={()=>void createBackup()} disabled={busy==='backup'}>整合バックアップを作成</button></div>{backup&&<div className="successBox">バックアップ: <code>{backup}</code></div>}{diag&&<div className="diagnosticGrid"><div><b>DB</b><code>{diag.database.path}</code><small>quick_check: {String(diag.database.quickCheck)}</small></div><div><b>Runtime</b><code>{diag.runtime.node}</code><small>{diag.runtime.cwd}</small></div><div><b>Counts</b><small>{Object.entries(diag.counts).map(([k,v])=>`${k} ${v}`).join(' · ')}</small></div></div>}<div className="hint">Gitはコードを保存しますが、SQLiteの調査データは別です。復元は停止中にCLIの restore 手順を使います。</div></section>
 </div>;
}
