import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api } from './api';

type Site={name:string;host:string;signal:string;error:boolean;clickChange?:number|null;sessionChange?:number|null;openTasks:number;openReviews:number;articleCount:number;verifiedArticles:number;publishedArticles:number;pendingEvaluations:number;improved:number;regressed:number;projects:Array<{id:string;name:string}>};
type Portfolio={sites:Site[];stale?:boolean;generatedAt?:string};
type AutoProject={recovery?:{state:string;newContentAllowed:boolean;observedAt:string|null;nextObservationAt:string|null;summary:{inspected:number;sampleSize:number;indexed:number;weeks:Array<{impressions:number}>}|null};id:string;name:string;domain?:string|null;control:{enabled:boolean;autoPublish:boolean;cadenceMinutes:number};state:{status:string;stage:string;lastTickAt?:string|null;nextTickAt?:string|null;lastError?:string|null};executor?:{id:string;status:string;connected:boolean}|null;openReviews:number};
type AutoPortfolio={projects:AutoProject[];totals:{projects:number;enabled:number;attention:number}};
const pct=(value?:number|null)=>value==null?'—':`${value>0?'+':''}${value.toFixed(1)}%`;

export function SitesOverview(){
 const [portfolio,setPortfolio]=useState<Portfolio|null>(null),[auto,setAuto]=useState<AutoPortfolio|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const load=async()=>{try{const [p,a]=await Promise.all([api<Portfolio>('/portfolio'),api<AutoPortfolio>('/autopilot/portfolio')]);setPortfolio(p);setAuto(a);setError('')}catch(e){setError(String(e))}};
 useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},15000);return()=>clearInterval(timer)},[]);
 const visible=useMemo(()=>portfolio?.sites.map(site=>({site,project:site.projects.map(p=>auto?.projects.find(a=>a.id===p.id)).find(Boolean)})).filter(({site,project})=>`${site.name} ${site.host}`.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='attention'&&(site.openReviews>0||site.regressed>0||site.error)||filter==='on'&&project?.control.enabled||filter==='off'&&!project?.control.enabled)).sort((a,b)=>Number(b.site.openReviews>0||b.site.regressed>0||b.site.error)-Number(a.site.openReviews>0||a.site.regressed>0||a.site.error)||a.site.name.localeCompare(b.site.name,'ja'))??[],[portfolio,auto,query,filter]);
 async function configure(projectId:string,patch:Record<string,unknown>){setBusy(projectId);try{await api(`/projects/${projectId}/autopilot/configure`,{method:'POST',body:JSON.stringify(patch)});await load()}catch(e){setError(String(e))}finally{setBusy('')}}
 async function createProject(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy('create');try{await api('/projects',{method:'POST',body:JSON.stringify({name:f.get('name'),domain:f.get('domain')})});form.reset();await load()}catch(e){setError(String(e))}finally{setBusy('')}}
 return <div className="corePage">
  <div className="coreTitleRow"><div><p className="coreEyebrow">SITES & SETTINGS</p><h1>サイト</h1><p>大量サイトでも、要対応を上に集めて状態と設定を同じ行で確認します。</p></div><span className="countBadge">{portfolio?.sites.length??0} sites</span></div>
  {error&&<div className="coreError">{error}<button onClick={()=>void load()}>再試行</button></div>}
  <div className="coreToolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="サイト名・ドメインを検索"/><div className="segmented"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>すべて</button><button className={filter==='attention'?'active':''} onClick={()=>setFilter('attention')}>要対応</button><button className={filter==='on'?'active':''} onClick={()=>setFilter('on')}>ON</button><button className={filter==='off'?'active':''} onClick={()=>setFilter('off')}>OFF</button></div><details className="createSite"><summary>＋ サイト追加</summary><form onSubmit={createProject}><input name="name" placeholder="サイト名" required/><input name="domain" placeholder="example.com"/><button disabled={busy==='create'}>{busy==='create'?'作成中…':'作成'}</button></form></details></div>
  <div className="siteListHeader"><span>サイト</span><span>記事</span><span>公開</span><span>評価待ち</span><span>改善 / 悪化</span><span>検索変化</span><span>Autopilot</span></div>
  <div className="siteList">{visible.map(({site,project})=><details className={`siteRow ${site.openReviews||site.regressed||site.error?'attention':''}`} key={site.host}><summary><span className="siteName"><i className={`stateDot ${site.error?'bad':site.openReviews||site.regressed?'warn':'good'}`}/><span><b>{site.name}</b><small>{site.host}</small></span></span><span><b>{site.articleCount}</b><small>{site.verifiedArticles} 検証済み</small></span><span><b>{site.publishedArticles}</b><small>公開済み</small></span><span><b>{site.pendingEvaluations}</b><small>観測中</small></span><span><b className="goodText">{site.improved}</b> / <b className={site.regressed?'badText':''}>{site.regressed}</b></span><span><b className={site.clickChange!=null&&site.clickChange<0?'badText':''}>{pct(site.clickChange)}</b><small>GSC clicks</small></span><span><i className={`togglePill ${project?.control.enabled?'on':'off'}`}>{project?.control.enabled?'ON':'OFF'}</i></span></summary><div className="siteExpanded"><div><h3>状態</h3><p>{site.signal}</p>{project?.recovery&&<p>新規記事：{project.recovery.newContentAllowed?'拡張可能':'回復確認まで保留'}<br/>{project.recovery.summary?`登録済み ${project.recovery.summary.indexed} / 検査済み ${project.recovery.summary.inspected} URL · 週別表示回数 ${project.recovery.summary.weeks.map(w=>w.impressions).join(' → ')||'未取得'}`:'URL検査・検索実績の計測待ち'}{project.recovery.nextObservationAt&&<small>次回観測 {new Date(project.recovery.nextObservationAt).toLocaleDateString('ja-JP')}</small>}</p>}<small>{site.openReviews?`${site.openReviews}件の判断待ち`:project?.state.lastError||'通常運転'}</small></div><div><h3>Agent</h3><p>{project?.executor?.connected?`${project.executor.id} · ${project.executor.status}`:'接続中のAgentなし'}</p><small>{project?.state.stage||'—'}{project?.state.nextTickAt?` · 次回 ${new Date(project.state.nextTickAt).toLocaleString('ja-JP')}`:''}</small></div><div className="siteControls"><h3>設定</h3>{project?<><label><span>Autopilot</span><button disabled={busy===project.id} className={`switchButton ${project.control.enabled?'on':''}`} onClick={e=>{e.preventDefault();void configure(project.id,{enabled:!project.control.enabled})}}>{project.control.enabled?'ON':'OFF'}</button></label><label><span>自動公開</span><button disabled={busy===project.id||!project.control.enabled} className={`switchButton ${project.control.autoPublish?'on':''}`} onClick={e=>{e.preventDefault();void configure(project.id,{autoPublish:!project.control.autoPublish})}}>{project.control.autoPublish?'ON':'OFF'}</button></label></>:<p>対応するproject設定がありません。</p>}</div></div></details>)}{visible.length===0&&<p className="coreEmpty">条件に一致するサイトはありません。</p>}</div>
 </div>;
}
