import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
process.env.KEYWORDS_DB_PATH=join(mkdtempSync(join(tmpdir(),'keywords-maintenance-')),'test.sqlite');
const {commands}=await import('@keywords/commands');
const {getDatabase}=await import('@keywords/db');
const {configureAutonomy}=await import('@keywords/commands/autonomy');
const {operationCommands}=await import('@keywords/commands/operation');
const {executorCommands}=await import('@keywords/commands/executor');
const {assertOperationAllowed}=await import('@keywords/commands/guard');
const {sqlite}=getDatabase();
const human={actor:'human' as const},system={actor:'system' as const,actorId:'maintenance'},agent={actor:'agent' as const,actorId:'worker'};
const fixtures:Array<{projectId:string;operationId:string;sessionId:string}>=[];
for(const kind of ['runtime','dns','review']){
  const project=await commands.project.create(human,{name:kind});
  await configureAutonomy(human,{projectId:project.id,enabled:true});
  const op=await operationCommands.start(human,{requestText:kind,projectIds:[project.id],constraints:{source:'autopilot',operatorKind:'sync_site'},budget:{maxActions:5,maxExternalRequests:5,maxRuntimeMinutes:2}});
  const child=op.children![0];
  const blocker=kind==='dns'?'DNS unavailable':'External agent process exited with code 1.';
  await operationCommands.checkpoint(human,{operationId:op.operation.id,projectId:project.id,state:kind==='review'?'awaiting_review':'blocked',summary:blocker,nextAction:'Resolve original condition'});
  sqlite.prepare('UPDATE operation_projects SET blocker_class=NULL WHERE operation_id=?').run(op.operation.id);
  fixtures.push({projectId:project.id,operationId:op.operation.id,sessionId:child.workSessionId});
}
const recovered=await executorCommands.recoverLegacyMaintenance(system,{});
assert.equal(recovered.recovered.length,1);
assert.equal(recovered.recovered[0].projectId,fixtures[0].projectId);
assert.equal((await operationCommands.context(human,{operationId:fixtures[1].operationId}) as any).status,'blocked');
assert.equal((await operationCommands.context(human,{operationId:fixtures[2].operationId}) as any).status,'awaiting_review');
assert.equal((await executorCommands.recoverLegacyMaintenance(system,{})).recovered.length,0,'Recovery is idempotent');
// Waiting in the queue for days must not consume the active runtime budget.
sqlite.prepare("UPDATE operation_requests SET created_at='2020-01-01T00:00:00.000Z' WHERE id=?").run(fixtures[0].operationId);
const registration=await operationCommands.executorRegister(agent,{executorId:agent.actorId});
const claim=await executorCommands.claimNext(agent,{generation:registration.generation,projectId:fixtures[0].projectId});
assert.ok(claim.claimed && 'operationId' in claim);
assert.equal(claim.remainingRuntimeMs,120000);
assert.doesNotThrow(()=>assertOperationAllowed({...agent,workSessionId:fixtures[0].sessionId},{projectId:fixtures[0].projectId,command:'site.sync_sitemap',capability:'site.sync'}));
const start=new Date(Date.now()-60000).toISOString(),expiry=new Date(Date.now()-30000).toISOString();
sqlite.prepare('UPDATE operation_projects SET runtime_started_at=? WHERE operation_id=?').run(start,fixtures[0].operationId);
sqlite.prepare('UPDATE operation_executors SET lease_expires_at=? WHERE id=?').run(expiry,agent.actorId);
assert.throws(()=>assertOperationAllowed({...agent,workSessionId:fixtures[0].sessionId},{projectId:fixtures[0].projectId,command:'site.sync_sitemap'}),/lease/);
await executorCommands.recoverStale(system,{});
const ledger=sqlite.prepare('SELECT runtime_consumed_ms,runtime_started_at FROM operation_projects WHERE operation_id=?').get(fixtures[0].operationId) as any;
assert.equal(ledger.runtime_consumed_ms,30000);
assert.equal(ledger.runtime_started_at,null);
const next=await operationCommands.executorRegister(agent,{executorId:agent.actorId});
const resumed=await executorCommands.claimNext(agent,{generation:next.generation,projectId:fixtures[0].projectId});
assert.ok(resumed.claimed && 'remainingRuntimeMs' in resumed);
assert.equal(resumed.remainingRuntimeMs,90000);
await operationCommands.executorRelease(agent,{generation:next.generation,operationId:fixtures[0].operationId,projectId:fixtures[0].projectId});
const consumed=(sqlite.prepare('SELECT runtime_consumed_ms FROM operation_projects WHERE operation_id=?').get(fixtures[0].operationId) as any).runtime_consumed_ms;
assert.ok(consumed>=30000&&consumed<31000);
console.log('PASS: runtime-only legacy recovery, real blockers preserved, idle time excluded, expired runtime capped, lease fencing');
