import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
process.env.KEYWORDS_DB_PATH = join(mkdtempSync(join(tmpdir(), 'keywords-recovery-')), 'test.sqlite');
process.env.GOOGLE_SEARCH_CONSOLE_ACCESS_TOKEN = 'fixture-only';
process.env.GOOGLE_SEARCH_CONSOLE_SITE_URL = 'sc-domain:example.com';
process.env.KEYWORDS_ALLOW_PRIVATE_FETCH = '1';
const { commands } = await import('@keywords/commands');
const { recoveryCommands } = await import('@keywords/commands/recovery');
const { getDatabase } = await import('@keywords/db');
const { recoveryCohort, recoveryContext, summarizeRecovery, dateOffset, recoveryDate } = await import('../packages/commands/src/recovery-context.js');
const { operationCommands } = await import('@keywords/commands/operation');
const { configureAutonomy } = await import('@keywords/commands/autonomy');
const { executorCommands } = await import('@keywords/commands/executor');
const { executeMaintenance } = await import('@keywords/commands/maintenance-execution');
const { sqlite } = getDatabase();
const human = { actor: 'human' as const, actorId: 'fixture-human' };
const agent = { actor: 'agent' as const, actorId: 'fixture-agent' };
const project = await commands.project.create(human, { name: 'Recovery', domain: 'en.example.com' });
const origin = 'https://en.example.com';
const now = new Date().toISOString();
sqlite.prepare('INSERT INTO blog_bindings(project_id,blog_site_id,origin,language,country,snapshot_json,snapshot_hash,observed_at) VALUES(?,?,?,?,?,?,?,?)').run(project.id, 'fixture', origin, 'en', 'US', JSON.stringify({ eligibility: { new_content_allowed: true, clearance_gate: 'listed_for_scoped_clearance', quality_status: 'healthy' } }), 'fixture', now);
for (let i=0;i<25;i++) {
  const page = await commands.page.propose(human, { projectId: project.id, title: `Page ${i}`, slug: `page-${i}` });
  sqlite.prepare("UPDATE pages SET url=?,status='published',source='sitemap' WHERE id=?").run(`${origin}/${i%2 ? 'blog' : 'guides'}/page-${i}/`, page.id);
}
assert.equal(recoveryContext(project.id).state, 'measurement_due');
const cohort = recoveryCohort(project.id, origin);
assert.equal(cohort.length,20);
assert.ok(cohort.some(url=>url.includes('/blog/')) && cohort.some(url=>url.includes('/guides/')));
let inspections = 0, failure = false;
globalThis.fetch = async (url, init) => {
  const body = JSON.parse(String(init?.body ?? '{}'));
  if (String(url).includes('urlInspection')) {
    inspections++;
    if (failure) return new Response('{}', {status:403});
    assert.equal(body.siteUrl, 'sc-domain:example.com');
    assert.ok(body.inspectionUrl.startsWith(origin+'/'));
    return Response.json({ inspectionResult: { indexStatusResult: { verdict: 'PASS', coverageState: 'Submitted and indexed', pageFetchState: 'SUCCESSFUL', googleCanonical: body.inspectionUrl, userCanonical: body.inspectionUrl } } });
  }
  assert.ok(String(url).includes('searchAnalytics/query'), 'Unexpected network request');
  assert.equal(body.dataState,'final');
  const filter = body.dimensionFilterGroups[0].filters[0];
  assert.equal(filter.dimension,'page');
  assert.ok(new RegExp(filter.expression).test(origin+'/blog/test/'));
  assert.ok(!new RegExp(filter.expression).test('https://ja.example.com/blog/test/'));
  return Response.json({rows: Array.from({length:21},(_,i)=>({keys:[dateOffset(body.startDate,i)],impressions:Math.floor(i/7)+1,clicks:0,position:4,ctr:0}))});
};
await configureAutonomy(human,{projectId:project.id,enabled:true});
const started = await operationCommands.start(human,{requestText:'Measure recovery',projectIds:[project.id],constraints:{operatorKind:'capture_recovery',measurementOnly:true},budget:{maxActions:5,maxExternalRequests:25,maxCandidateWrites:0,maxProjects:1,maxRuntimeMinutes:2}});
await assert.rejects(()=>operationCommands.complete(human,{operationId:started.operation.id,summary:'No evidence'}),/evidence/);
const registration = await operationCommands.executorRegister(agent,{executorId:agent.actorId});
const claim = await executorCommands.claimNext(agent,{executorId:agent.actorId,generation:registration.generation,projectId:project.id});
assert.equal(claim.claimed,true);
assert.equal((await executeMaintenance(agent,claim)).handled,true);
await operationCommands.executorRelease(agent,{executorId:agent.actorId,generation:registration.generation,operationId:claim.operationId,projectId:project.id});
const healthy = recoveryContext(project.id);
assert.equal(healthy.newContentAllowed,true);
assert.equal(inspections,20);
assert.deepEqual(healthy.summary?.weeks.map(week=>week.impressions),[7,14,21]);
assert.deepEqual(recoveryCohort(project.id,origin),cohort);
const again = await recoveryCommands.capture(human,{projectId:project.id});
assert.equal(again.requests,1,'Recent inspections are reused');
assert.equal(inspections,20);
const partial = structuredClone(healthy.latest!);
partial.inspections.pop(); partial.complete=false; partial.daily=null;
assert.equal(summarizeRecovery(partial).recovered,false);
assert.equal(summarizeRecovery(partial).weeks.length,0);
const conflict=structuredClone(healthy.latest!); conflict.inspections[0].googleCanonical='https://ja.example.com/';
assert.equal(summarizeRecovery(conflict).recovered,false);
sqlite.prepare("UPDATE sources SET created_at='2020-01-01' WHERE type='gsc_url_inspection'").run();
failure=true;
const incomplete = await recoveryCommands.capture(human,{projectId:project.id});
assert.equal(incomplete.complete,false);
assert.equal(incomplete.requests,1,'Auth failure does not consume 20 requests');
assert.equal(incomplete.recovery.newContentAllowed,false);
assert.equal(incomplete.recovery.summary?.indexRate,null,'API failure is not deindexation');
assert.equal(incomplete.recovery.summary?.weeks.length,0,'API failure is not zero traffic');
await assert.rejects(()=>recoveryCommands.capture(human,{projectId:project.id,endDate:dateOffset(recoveryDate(),1)}),/complete Search Console/);
const paused=await operationCommands.start(human,{requestText:'Pause boundary',projectIds:[project.id]});
await operationCommands.checkpoint(human,{operationId:paused.operation.id,projectId:project.id,state:'blocked',summary:'Dependency',nextAction:'Resolve dependency'});
const count=inspections;
await assert.rejects(()=>recoveryCommands.capture(agent,{projectId:project.id}),/Attach work session/);
assert.equal(inspections,count);
console.log('PASS: scoped fixed cohort, real command evidence, reuse, incomplete/auth failure, expansion and pause boundaries');
