import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const root=mkdtempSync(join(tmpdir(),'keywords-site-runtime-'));
process.env.KEYWORDS_DB_PATH=join(root,'test.sqlite');
process.env.KEYWORDS_BLOG_WORKSPACE_ROOT=root;
process.env.KEYWORDS_BLOG_ROOT=join(root,'wrong');
process.env.KEYWORDS_ALLOW_PRIVATE_FETCH='1';
const {commands}=await import('@keywords/commands');
const {getDatabase}=await import('@keywords/db');
const {articleRuntime,safeArtifactPath}=await import('../packages/commands/src/headless.js');
const {portfolioCommands}=await import('@keywords/commands/portfolio');
const {readBlogRuntime,newBlogArticleTarget}=await import('@keywords/research/blog-runtime');
const {fetchSitemapUrls}=await import('@keywords/research/sitemap');
const {sqlite}=getDatabase();
const human={actor:'human' as const},t=new Date().toISOString();
mkdirSync(join(root,'.seo-autopilot/integration/sites'),{recursive:true});
const sites=['one','two'].map(id=>({id,path:join(root,id),build_command:`node build-${id}.mjs`}));
writeFileSync(join(root,'.seo-autopilot/sites.json'),JSON.stringify({sites}));
const projectIds:string[]=[];
for(const site of sites){
  const origin=`https://${site.id}.example.com`;
  mkdirSync(join(site.path,'src/content/blog'),{recursive:true});
  writeFileSync(join(site.path,'src/content/blog/same.md'),`---\ntitle: ${site.id}\n---\nDifferent site ${site.id}`);
  writeFileSync(join(root,`.seo-autopilot/integration/sites/${site.id}.json`),JSON.stringify({blog_site_id:site.id,canonical_origin:origin,collections:[{root:'src/content/blog',extensions:['.md'],url_template:'/blog/{slug}/'}]}));
  const project=await commands.project.create(human,{name:site.id,domain:`${site.id}.example.com`});projectIds.push(project.id);
  sqlite.prepare('INSERT INTO blog_bindings(project_id,blog_site_id,origin,language,country,snapshot_json,snapshot_hash,observed_at) VALUES(?,?,?,?,?,?,?,?)').run(project.id,site.id,origin,'en','US','{}','fixture',t);
  assert.equal(articleRuntime(project.id).buildCommand,site.build_command);
  assert.equal(readFileSync(safeArtifactPath('src/content/blog/same.md',project.id).absolute,'utf8').includes(`Different site ${site.id}`),true);
  assert.throws(()=>safeArtifactPath('../two/src/content/blog/same.md',project.id),/safe relative path/);
  assert.equal(newBlogArticleTarget(readBlogRuntime(site.id,origin),origin,'new').url,`${origin}/blog/new/`);
}
const index=await portfolioCommands.articleIndex();
assert.equal(index.total,2);
assert.equal(new Set(index.items.map(item=>item.id)).size,2,'Same relative path in two sites has distinct identity');
const content=await portfolioCommands.articleContent(index.items.find(item=>item.projectId===projectIds[1])!.id);
assert.ok(content.content.includes('Different site two'));
assert.throws(()=>readBlogRuntime('one','https://two.example.com'),/bound origin/);
let fetched:string[]=[];
globalThis.fetch=async url=>{
  const u=String(url);fetched.push(u);
  if(u.endsWith('/sitemap.xml'))return new Response('',{status:404});
  if(u.endsWith('/robots.txt'))return new Response('Sitemap: https://one.example.com/sitemap-index.xml');
  if(u.endsWith('/sitemap-index.xml'))return new Response('<sitemapindex><sitemap><loc>https://one.example.com/sitemap-0.xml</loc></sitemap></sitemapindex>');
  if(u.endsWith('/sitemap-0.xml'))return new Response('<urlset><url><loc>https://one.example.com/blog/same/</loc></url><url><loc>https://two.example.com/blog/same/</loc></url></urlset>');
  throw Error(`Unexpected fixture URL ${u}`);
};
let charged=0;
const sitemap=await fetchSitemapUrls({sitemapUrl:'https://one.example.com/sitemap.xml',discover:true,onRequest:async()=>{charged++;}});
assert.equal(sitemap.sitemapUrl,'https://one.example.com/sitemap-index.xml');
assert.deepEqual(sitemap.urls,['https://one.example.com/blog/same/']);
assert.equal(sitemap.rejectedUrls,1);
assert.equal(sitemap.complete,false,'Rejected inventory cannot mark other URLs stale');
assert.equal(charged,fetched.length);
globalThis.fetch=async()=>new Response('<html>Not a sitemap</html>');
await assert.rejects(()=>fetchSitemapUrls({sitemapUrl:'https://one.example.com/sitemap.xml'}),/XML|sitemap/i);
console.log('PASS: per-site roots/builds/routes/article identity and sitemap fallback/partial boundaries');
