/** Task-specific instructions are carried by the shared Operation, not private agent state. */
export function operatorInstructions(next: Record<string, unknown>) {
  const kind = String(next.kind ?? 'no_action');
  const observation = kind === 'capture_recovery';
  const measurement = ['capture_metrics','observe_outcome','blog_observation_due'].includes(kind);
  const siteOptimization = kind === 'evaluate_site_optimization';
  const queryFeedback = kind === 'research_site_queries';
  const inventory = kind === 'sync_site';
  const recovery = kind === 'recover_existing_page';
  const objective = `${String(next.title ?? kind)}. ${String(next.reason ?? '')}`.slice(0, 1000);
  const common = 'Read work_context, policy_context and operation_context. Respect existing pauses, human reviews, scoped new-content clearance and action budgets. Never invent experience, measurements, citations, publication or Google quality verdicts. Never delete pages, move URLs, change DNS or activate policy rules.';
  const instructions = observation
    ? 'Call recovery_context, then recovery_capture. The command selects a stable cohort, discovers the matching Search Console property if needed, and persists URL inspections and 21 complete days. Read the returned recovery state and record the next observation date. This is a measurement-only operation; no page plan or article is required.'
    : inventory
    ? 'Call site_sync. Use the previously successful sitemap or robots.txt discovery when the default sitemap is absent. Preserve previous observations on network failure or truncated import. This is an inventory operation; do not create a page plan or article.'
    : siteOptimization
    ? `Call site_optimization_evaluation_context with projectId and eventId=${String(next.relatedId ?? '')}. Read the persisted observation, diagnosis and hypothesis before interpreting the deltas. If readyForAgentEvaluation is false, checkpoint the operation with the concrete missing evidence and do not invent a verdict. If it is true, classify only the persisted hypothesis as improved, neutral, worsened or inconclusive, explain the decision briefly, then call site_optimization_record_result with eventId=${String(next.relatedId ?? '')}, the current event revision and that verdict. Numerical evaluation metrics are recomputed by the command from saved snapshots. Do not edit the article, run new research, or start another optimization in this evaluation-only operation.`
    : queryFeedback
    ? `Research only the pinned Search Console feedback batch from snapshot ${String(next.relatedId ?? '')}. The saved candidate evidence is: ${JSON.stringify(next.feedbackCandidates ?? []).slice(0, 12000)}. Call keyword_research_pipeline once with exactly those query strings and maxSerpChecks=${Number(next.maxSerpChecks ?? 5)}; that command performs Google Ads screening first and spends cached/quota-aware SERP only on shortlisted terms. Do not call research_serp directly for this batch. Review the Ads and SERP evidence, then call keyword_treasury_save only for candidates worth retaining. Preserve provenance with source='gsc_feedback' and evidence containing siteId=${String(next.siteId ?? '')}, snapshotId=${String(next.relatedId ?? '')}, previousSnapshotId=${String(next.previousSnapshotId ?? '')}, the GSC candidate row, demand metrics and SERP evidence when available. This is research-only: do not create or modify an article or Site Concept, and do not save every observed query automatically.`
    : measurement
    ? 'Read the persisted outcome/handoff and measurement context. Capture comparable complete periods for the bound origin, preserving source IDs and the publication date. Use blog_evaluate for a Blog handoff. Small samples are inconclusive, with a future observation date. Do not invent a result or create an article for this measurement operation.'
    : recovery
    ? `Read recovery_context and source ${String(next.observationSourceId ?? '')}. Inspect the actual existing page ${String(next.targetUrl ?? next.relatedId ?? '')}, its mapped local source and relevant first-party evidence. Determine the concrete reason the page does not satisfy its reader task. Use existing_page_improvement with targetPageId=${String(next.relatedId ?? '')}; keep the URL. Write and validate any article change through blog_writeDraft/blog_validateDraft and the site's real build. If a change is not justified, persist an insight linked to the observation explaining why. Do not create filler, an unmapped Markdown article, or a new keyword page. Structural changes outside the article adapter require an explicit reviewable proposal. Record a hypothesis and a pending outcome for an actual change; local validation is not publication or SEO recovery.`
    : 'Gather evidence that can change the decision, then make the smallest justified improvement. For content, read blog_contract, prepare the evidence brief, write the actual mapped artifact with blog_writeDraft and verify with blog_validateDraft and the real site build. A page plan alone is not completion. Read recovery_context before proposing expansion. Record the next measurable condition.';
  return { objective, instructions: `${common}\n\n${instructions}`, measurementOnly: observation || measurement || inventory || siteOptimization || queryFeedback,
    completionCriteria: observation ? ['Persist the fixed-cohort recovery observation through recovery_capture.', 'Keep incomplete/API failure results distinct from zero visibility.', 'Record the next observation date.']
      : inventory ? ['Persist a successful same-origin sitemap inventory through site_sync.', 'Do not treat a local snapshot as live publication.']
      : siteOptimization ? ['Read the compatible persisted evaluation packet.', 'Persist exactly one evidence-backed result through site_optimization_record_result, or checkpoint the concrete missing evidence.', 'Do not modify article content in the evaluation operation.']
      : queryFeedback ? ['Research the exact pinned GSC query batch through keyword_research_pipeline.', 'Keep SERP checks within the operation maxSerpChecks bound.', 'Save only selected evidence-backed candidates to Keyword Treasury with GSC snapshot provenance.', 'Do not create or modify site content in this research operation.']
      : recovery ? ['Persist a validated existing-page improvement or a source-linked no-change finding.', 'Keep the target URL and record the next measurable condition.']
      : ['Persist the evidence and the result appropriate to this operation.', 'Verify any article change with its real site build before completion.', 'Record a measurable next condition.'] };
}
