import { Command } from 'commander';
import { commands } from '@keywords/commands';
const program = new Command();
const ctx = { actor: 'human' as const, actorId: process.env.USER ?? 'cli' };
const print = (value: unknown) => console.log(JSON.stringify(value, null, 2));
program.name('keywords').description('Agent-native SEO workspace CLI');
const project = program.command('project');
project.command('list').action(async () => print(await commands.project.list(ctx)));
project.command('create').argument('<name>').option('--domain <domain>').action(async (name: string, opts: {domain?: string}) => print(await commands.project.create(ctx, { name, domain: opts.domain })));
project.command('snapshot').argument('<projectId>').action(async (projectId: string) => print(await commands.project.snapshot(ctx, projectId)));
const keyword = program.command('keyword');
keyword.command('list').argument('<projectId>').action(async (projectId: string) => print(await commands.keyword.list(ctx, projectId)));
keyword.command('add').argument('<projectId>').argument('<text>').option('--volume <number>').action(async (projectId: string, text: string, opts: {volume?: string}) => print(await commands.keyword.create(ctx, { projectId, text, avgMonthly: opts.volume ? Number(opts.volume) : undefined })));
keyword.command('reject').argument('<projectId>').argument('<keywordId>').option('--reason <reason>').action(async (projectId: string, keywordId: string, opts: {reason?: string}) => print(await commands.keyword.reject(ctx, { projectId, keywordId, reason: opts.reason })));
const cluster = program.command('cluster');
cluster.command('list').argument('<projectId>').action(async (projectId: string) => print(await commands.cluster.list(ctx, projectId)));
cluster.command('create').argument('<projectId>').argument('<title>').option('--intent <intent>').action(async (projectId: string, title: string, opts: {intent?: string}) => print(await commands.cluster.create(ctx, { projectId, title, intent: opts.intent })));
const task = program.command('task');
task.command('list').argument('<projectId>').action(async (projectId: string) => print(await commands.task.list(ctx, projectId)));
task.command('add').argument('<projectId>').argument('<title>').option('--priority <number>').action(async (projectId: string, title: string, opts: {priority?: string}) => print(await commands.task.create(ctx, { projectId, title, priority: opts.priority ? Number(opts.priority) : undefined })));
await program.parseAsync();
