import { Command } from 'commander';
import { commands } from '@keywords/commands';
const program = new Command();
const ctx = { actor: 'human' as const, actorId: process.env.USER ?? 'cli' };
const print = (value: unknown) => console.log(JSON.stringify(value, null, 2));
program.name('keywords').description('Agent-native SEO workspace CLI');
const project = program.command('project');
project.command('list').action(async () => print(await commands.project.list(ctx)));
project.command('create').argument('<name>').option('--domain <domain>').action(async (name: string, opts: {domain?: string}) => print(await commands.project.create(ctx, { name, domain: opts.domain })));
project.command('snapshot').argument('<projectId>').action(async (projectId: string) => print(await commands.project.snapshot(ctx, projectId)));
const source = program.command('source');
source.command('list').argument('<projectId>').option('--type <type>').action(async (projectId: string, opts: {type?: string}) => print(await commands.source.list(ctx, projectId, opts.type)));
const research = program.command('research');
research.command('context').argument('<projectId>').action(async (projectId: string) => print(await commands.research.context(ctx, projectId)));
research.command('web').argument('<projectId>').argument('<url>').option('--max-chars <number>').action(async (projectId: string, url: string, opts: {maxChars?: string}) => print(await commands.research.webFetch(ctx, { projectId, url, maxChars: opts.maxChars ? Number(opts.maxChars) : undefined })));
research.command('serp').argument('<projectId>').argument('<query>').option('--country <country>').option('--language <language>').option('--location <location>').option('--num <number>').action(async (projectId: string, query: string, opts: {country?: string; language?: string; location?: string; num?: string}) => print(await commands.research.serp(ctx, { projectId, query, country: opts.country, language: opts.language, location: opts.location, num: opts.num ? Number(opts.num) : undefined })));
research.command('ads').argument('<projectId>').argument('[seeds...]').option('--url <url>').option('--customer <customerId>').option('--language-id <id>').option('--geo <ids>').option('--no-import').action(async (projectId: string, seeds: string[] | undefined, opts: {url?: string; customer?: string; languageId?: string; geo?: string; import: boolean}) => print(await commands.research.googleAdsKeywordIdeas(ctx, { projectId, customerId: opts.customer, seedKeywords: seeds ?? [], url: opts.url, languageId: opts.languageId, geoTargetIds: opts.geo?.split(',').map(value => value.trim()).filter(Boolean), importKeywords: opts.import })));
research.command('gsc').argument('<projectId>').argument('<startDate>').argument('<endDate>').option('--site <siteUrl>').option('--dimensions <csv>', 'Comma-separated dimensions', 'query').option('--row-limit <number>').option('--search-type <type>').option('--no-import').action(async (projectId: string, startDate: string, endDate: string, opts: {site?: string; dimensions: string; rowLimit?: string; searchType?: string; import: boolean}) => print(await commands.research.searchConsole(ctx, { projectId, siteUrl: opts.site, startDate, endDate, dimensions: opts.dimensions.split(',').map(value => value.trim()).filter(Boolean), rowLimit: opts.rowLimit ? Number(opts.rowLimit) : undefined, searchType: opts.searchType, importQueries: opts.import })));
const keyword = program.command('keyword');
keyword.command('list').argument('<projectId>').action(async (projectId: string) => print(await commands.keyword.list(ctx, projectId)));
keyword.command('add').argument('<projectId>').argument('<text>').option('--volume <number>').action(async (projectId: string, text: string, opts: {volume?: string}) => print(await commands.keyword.create(ctx, { projectId, text, avgMonthly: opts.volume ? Number(opts.volume) : undefined })));
keyword.command('reject').argument('<projectId>').argument('<keywordId>').option('--reason <reason>').action(async (projectId: string, keywordId: string, opts: {reason?: string}) => print(await commands.keyword.reject(ctx, { projectId, keywordId, reason: opts.reason })));
const cluster = program.command('cluster');
cluster.command('list').argument('<projectId>').action(async (projectId: string) => print(await commands.cluster.list(ctx, projectId)));
cluster.command('create').argument('<projectId>').argument('<title>').option('--intent <intent>').action(async (projectId: string, title: string, opts: {intent?: string}) => print(await commands.cluster.create(ctx, { projectId, title, intent: opts.intent })));
const task = program.command('task');
task.command('list').argument('<projectId>').action(async (projectId: string) => print(await commands.task.list(ctx, projectId)));
task.command('add').argument('<projectId>').argument('<title>').option('--priority <number>').action(async (projectId: string, title: string, opts: {priority?: string}) => print(await commands.task.create(ctx, { projectId, title, priority: opts.priority ? Number(opts.priority) : undefined })));
await program.parseAsync();
