import type { Command } from 'commander';
import type { CommandContext } from '@keywords/domain';
import { discoveryCommands } from '@keywords/commands/discovery';
import { workspaceCommands } from '@keywords/commands/workspace';
import { maintenanceCommands } from '@keywords/commands/maintenance';
import { operationCommands } from '@keywords/commands/operation';
import { operationDiscoveryCommands } from '@keywords/commands/operation-discovery';
import { measurementCommands } from '@keywords/commands/measurement';
import { metricsCommands } from '@keywords/commands/metrics';
import { recoveryCommands } from '@keywords/commands/recovery';

const print = (value: unknown) => console.log(JSON.stringify(value, null, 2));
const csv = (value?: string) => value?.split(',').map(item => item.trim()).filter(Boolean) ?? [];
const json = (value?: string) => value ? JSON.parse(value) : undefined;
const agentCtx = (ctx: CommandContext, workSessionId?: string) => ({ ...ctx, actor: 'agent' as const, actorId: `${ctx.actorId ?? 'cli'}:agent`, workSessionId });

export function registerProductCli(program: Command, ctx: CommandContext) {
  const recovery = program.command('recovery').description('Index recovery and scoped search observations');
  recovery.command('context').argument('<projectId>').action(async (projectId: string) => print(await recoveryCommands.context(ctx, { projectId })));
  recovery.command('capture').argument('<projectId>').option('--property <siteUrl>').option('--end <date>').option('--session <workSessionId>').option('--actor-id <id>', 'Executor identity', process.env.KEYWORDS_AGENT_ID ?? 'mcp')
    .action(async (projectId: string, opts: any) => print(await recoveryCommands.capture({ actor: 'agent', actorId: opts.actorId, workSessionId: opts.session }, { projectId, siteUrl: opts.property, endDate: opts.end })));
  const operation = program.command('operation').description('Durable agent-driven operations');
  operation.command('context').option('--project <projectId>').option('--operation <operationId>').action(async (opts: any) => print(await operationCommands.context(ctx, { projectId: opts.project, operationId: opts.operation })));
  operation.command('start').argument('<request>').option('--projects <csv>').option('--scope <scope>', 'single | portfolio', 'single').option('--conversation <ref>').option('--objective <text>').option('--criteria <csv>').option('--max-actions <number>', '16').option('--max-requests <number>', '10').option('--max-candidates <number>', '80').option('--max-projects <number>', '1').option('--runtime-minutes <number>', '45')
    .action(async (request: string, opts: any) => print(await operationCommands.start(ctx, { requestText: request, projectIds: opts.projects ? csv(opts.projects) : undefined, scope: opts.scope, conversationRef: opts.conversation, objective: opts.objective, completionCriteria: opts.criteria ? csv(opts.criteria) : undefined, budget: { maxActions: Number(opts.maxActions), maxExternalRequests: Number(opts.maxRequests), maxCandidateWrites: Number(opts.maxCandidates), maxProjects: Number(opts.maxProjects), maxRuntimeMinutes: Number(opts.runtimeMinutes) } })));
  operation.command('resume').argument('<operationId>').option('--project <projectId>').action(async (operationId: string, opts: any) => print(await operationCommands.resume(ctx, { operationId, projectId: opts.project })));
  operation.command('cancel').argument('<operationId>').requiredOption('--reason <text>').action(async (operationId: string, opts: any) => print(await operationCommands.cancel(ctx, { operationId, reason: opts.reason })));
  operation.command('checkpoint').argument('<operationId>').argument('<projectId>').argument('<state>', 'working | awaiting_review | blocked').requiredOption('--summary <text>').option('--next <text>').option('--session <workSessionId>').action(async (operationId: string, projectId: string, state: any, opts: any) => print(await operationCommands.checkpoint(agentCtx(ctx, opts.session), { operationId, projectId, state, summary: opts.summary, nextAction: opts.next })));
  operation.command('complete').argument('<operationId>').requiredOption('--summary <text>').action(async (operationId: string, opts: any) => print(await operationCommands.complete(ctx, { operationId, summary: opts.summary })));
  operation.command('discovery-start').argument('<operationId>').argument('<projectId>').requiredOption('--goal <text>').option('--seeds <csv>').option('--url <url>').option('--exclude <csv>').option('--demand-policy <policy>', 'required | surface_only', 'required').option('--max-candidates <number>').option('--max-requests <number>').option('--lease-seconds <number>', '300').option('--session <workSessionId>')
    .action(async (operationId: string, projectId: string, opts: any) => print(await operationDiscoveryCommands.startAndClaim(agentCtx(ctx, opts.session), { operationId, projectId, goal: opts.goal, seedKeywords: csv(opts.seeds), targetUrl: opts.url, excludedTerms: opts.exclude === undefined ? undefined : csv(opts.exclude), demandPolicy: opts.demandPolicy, maxCandidates: opts.maxCandidates ? Number(opts.maxCandidates) : undefined, maxExternalRequests: opts.maxRequests ? Number(opts.maxRequests) : undefined, leaseSeconds: Number(opts.leaseSeconds) })));
  operation.command('triage').argument('<operationId>').argument('<projectId>').argument('<jobId>').requiredOption('--candidates <csv>').requiredOption('--status <status>').requiredOption('--reason <text>').option('--session <workSessionId>').action(async (operationId: string, projectId: string, jobId: string, opts: any) => print(await operationCommands.triageCandidates(agentCtx(ctx, opts.session), { operationId, projectId, jobId, candidateIds: csv(opts.candidates), status: opts.status, reason: opts.reason })));
  operation.command('outcome').argument('<projectId>').requiredOption('--status <status>').option('--operation <operationId>').option('--target-url <url>').option('--handoff <id>').option('--hypothesis <text>').option('--implemented-at <iso>').option('--published-at <iso>').option('--evaluation-due-at <iso>').option('--metrics <json>').option('--attribution <text>').option('--next <text>').option('--session <workSessionId>')
    .action(async (projectId: string, opts: any) => print(await operationCommands.recordOutcome(agentCtx(ctx, opts.session), { operationId: opts.operation, projectId, targetUrl: opts.targetUrl, handoffId: opts.handoff, hypothesis: opts.hypothesis, implementedAt: opts.implementedAt, publishedAt: opts.publishedAt, evaluationDueAt: opts.evaluationDueAt, status: opts.status, metrics: json(opts.metrics), attributionNotes: opts.attribution, nextAction: opts.next })));
  operation.command('outcomes').option('--project <projectId>').option('--status <status>').option('--limit <number>', '50').action(async (opts: any) => print(await operationCommands.listOutcomes(ctx, { projectId: opts.project, status: opts.status, limit: Number(opts.limit) })));
  operation.command('pause').argument('<projectId>').option('--reason <text>').action(async (projectId: string, opts: any) => print(await operationCommands.setPause(ctx, { projectId, paused: true, reason: opts.reason })));
  operation.command('unpause').argument('<projectId>').action(async (projectId: string) => print(await operationCommands.setPause(ctx, { projectId, paused: false })));
  operation.command('delegations').argument('<projectId>').action(async (projectId: string) => print(await operationCommands.delegationList(ctx, projectId)));
  operation.command('delegate').argument('<projectId>').argument('<capability>').option('--limits <json>').option('--expires-at <iso>').action(async (projectId: string, capability: string, opts: any) => print(await operationCommands.delegationGrant(ctx, { projectId, capability, limits: json(opts.limits), expiresAt: opts.expiresAt })));
  operation.command('revoke').argument('<projectId>').argument('<delegationId>').option('--reason <text>').action(async (projectId: string, delegationId: string, opts: any) => print(await operationCommands.delegationRevoke(ctx, { projectId, delegationId, reason: opts.reason })));
  operation.command('executor-register').option('--id <executorId>').option('--capabilities <csv>').option('--lease-seconds <number>', '300').action(async (opts: any) => print(await operationCommands.executorRegister(agentCtx(ctx), { executorId: opts.id, capabilities: csv(opts.capabilities), leaseSeconds: Number(opts.leaseSeconds) })));
  operation.command('executor-heartbeat').argument('<generation>').option('--id <executorId>').option('--lease-seconds <number>', '300').action(async (generation: string, opts: any) => print(await operationCommands.executorHeartbeat(agentCtx(ctx), { executorId: opts.id, generation: Number(generation), leaseSeconds: Number(opts.leaseSeconds) })));
  operation.command('executor-claim').argument('<generation>').argument('<operationId>').argument('<projectId>').option('--id <executorId>').option('--lease-seconds <number>', '300').option('--session <workSessionId>').action(async (generation: string, operationId: string, projectId: string, opts: any) => print(await operationCommands.executorClaim(agentCtx(ctx, opts.session), { executorId: opts.id, generation: Number(generation), operationId, projectId, leaseSeconds: Number(opts.leaseSeconds) })));
  operation.command('remote-readiness').action(async () => print(await operationCommands.remoteReadiness(ctx)));

  const measurement = program.command('measurement').description('Versioned measurement contract');
  measurement.command('context').argument('<projectId>').option('--limit <number>', '25').action(async (projectId: string, opts: any) => print(await measurementCommands.context(ctx, projectId, Number(opts.limit))));
  measurement.command('list').argument('<projectId>').option('--provider <provider>').option('--limit <number>', '50').action(async (projectId: string, opts: any) => print(await measurementCommands.list(ctx, { projectId, provider: opts.provider, limit: Number(opts.limit) })));
  measurement.command('capture').argument('<projectId>').argument('<startDate>').argument('<endDate>').option('--property <siteUrl>').option('--origin <targetOrigin>').option('--search-type <type>', 'web').option('--timezone <timezone>', 'UTC').option('--row-limit <number>', '25000').action(async (projectId: string, startDate: string, endDate: string, opts: any) => print(await metricsCommands.capture(ctx, { projectId, startDate, endDate, siteUrl: opts.property, targetOrigin: opts.origin, searchType: opts.searchType, timezone: opts.timezone, rowLimit: Number(opts.rowLimit) })));
  measurement.command('import').argument('<projectId>').requiredOption('--provider <provider>').requiredOption('--property <property>').requiredOption('--start <date>').requiredOption('--end <date>').requiredOption('--dimensions <csv>').requiredOption('--status <status>').requiredOption('--completeness <state>').requiredOption('--label <text>').requiredOption('--version <version>').requiredOption('--captured-at <iso>').option('--origin <origin>').option('--filters <json>').option('--timezone <timezone>', 'UTC').option('--search-type <type>').option('--payload <json>').option('--session <workSessionId>').action(async (projectId: string, opts: any) => print(await measurementCommands.import(agentCtx(ctx, opts.session), { projectId, provider: opts.provider, property: opts.property, targetOrigin: opts.origin, filters: json(opts.filters), startDate: opts.start, endDate: opts.end, timezone: opts.timezone, searchType: opts.searchType, dimensions: csv(opts.dimensions), status: opts.status, completeness: opts.completeness, sourceLabel: opts.label, sourceVersion: opts.version, capturedAt: opts.capturedAt, payload: json(opts.payload) })));

  const workspace = program.command('workspace');
  workspace.command('brief').argument('<projectId>').action(async (projectId: string) => print(await workspaceCommands.brief(ctx, projectId)));
  workspace.command('capabilities').argument('<projectId>').action(async (projectId: string) => print(await workspaceCommands.capabilities(ctx, projectId)));
  workspace.command('configure').argument('<projectId>')
    .option('--mode <mode>', 'existing_site | topic_only').option('--domain <domain>').option('--topic <topic>').option('--audience <audience>')
    .option('--language <language>').option('--country <country>').option('--region <region>').option('--exclude <csv>')
    .option('--cadence-days <number>').option('--max-candidates <number>').option('--max-requests <number>')
    .action(async (projectId: string, opts: any) => print(await workspaceCommands.updateBrief(ctx, {
      projectId, mode: opts.mode, domain: opts.domain, topic: opts.topic, audience: opts.audience, language: opts.language, country: opts.country, region: opts.region,
      excludedTerms: opts.exclude === undefined ? undefined : csv(opts.exclude), discoveryCadenceDays: opts.cadenceDays ? Number(opts.cadenceDays) : undefined,
      discoveryMaxCandidates: opts.maxCandidates ? Number(opts.maxCandidates) : undefined, discoveryMaxExternalRequests: opts.maxRequests ? Number(opts.maxRequests) : undefined
    })));
  workspace.command('keywords').argument('<projectId>')
    .option('--query <text>').option('--candidate-status <status>').option('--cluster <clusterId>')
    .option('--existing-page <state>', 'with | without').option('--research-status <state>', 'researched | unresearched | failed')
    .option('--provider <provider>').option('--sort <sort>', 'demand_desc | keyword_asc | gsc_impressions_desc | updated_desc', 'demand_desc')
    .option('--limit <number>', 'Rows', '50').option('--offset <number>', 'Offset', '0')
    .action(async (projectId: string, opts: any) => print(await workspaceCommands.keywordSearch(ctx, {
      projectId, q: opts.query, candidateStatus: opts.candidateStatus, clusterId: opts.cluster, existingPage: opts.existingPage,
      researchStatus: opts.researchStatus, provider: opts.provider, sort: opts.sort, limit: Number(opts.limit), offset: Number(opts.offset)
    })));
  workspace.command('keyword-detail').argument('<projectId>').argument('<keywordId>').action(async (projectId: string, keywordId: string) => print(await workspaceCommands.keywordDetail(ctx, { projectId, keywordId })));
  workspace.command('continuous').argument('<projectId>').action(async (projectId: string) => print(await workspaceCommands.continuousSummary(ctx, projectId)));

  const discovery = program.command('discovery');
  discovery.command('list').argument('<projectId>').action(async (projectId: string) => print(await discoveryCommands.list(ctx, projectId)));
  discovery.command('show').argument('<projectId>').argument('<jobId>').action(async (projectId: string, jobId: string) => print(await discoveryCommands.detail(ctx, { projectId, jobId })));
  discovery.command('start').argument('<projectId>').requiredOption('--goal <text>').option('--seeds <csv>').option('--url <url>').option('--language <language>').option('--country <country>').option('--region <region>').option('--exclude <csv>').option('--demand-policy <policy>', 'required | surface_only', 'required').option('--max-candidates <number>').option('--max-requests <number>')
    .action(async (projectId: string, opts: any) => print(await discoveryCommands.start(ctx, { projectId, goal: opts.goal, seedKeywords: csv(opts.seeds), targetUrl: opts.url, language: opts.language, country: opts.country, region: opts.region, excludedTerms: opts.exclude === undefined ? undefined : csv(opts.exclude), demandPolicy: opts.demandPolicy, maxCandidates: opts.maxCandidates ? Number(opts.maxCandidates) : undefined, maxExternalRequests: opts.maxRequests ? Number(opts.maxRequests) : undefined })));
  discovery.command('claim').argument('<projectId>').argument('<jobId>').option('--lease-seconds <number>', 'Executor lease', '120').description('Claim as a local CLI agent for debugging/automation').action(async (projectId: string, jobId: string, opts: any) => print(await discoveryCommands.claim(agentCtx(ctx), { projectId, jobId, leaseSeconds: Number(opts.leaseSeconds) })));
  discovery.command('heartbeat').argument('<projectId>').argument('<jobId>').option('--lease-seconds <number>', 'Extend lease', '120').action(async (projectId: string, jobId: string, opts: any) => print(await discoveryCommands.heartbeat(agentCtx(ctx), { projectId, jobId, leaseSeconds: Number(opts.leaseSeconds) })));
  discovery.command('recover').argument('<projectId>').argument('<jobId>').description('Recover a running discovery whose executor lease expired').action(async (projectId: string, jobId: string) => print(await discoveryCommands.recoverExpired(ctx, { projectId, jobId })));
  discovery.command('ads').argument('<projectId>').argument('<jobId>').option('--seeds <csv>').option('--url <url>').option('--idempotency-key <key>').action(async (projectId: string, jobId: string, opts: any) => print(await discoveryCommands.adsIdeas(agentCtx(ctx), { projectId, jobId, seedKeywords: opts.seeds ? csv(opts.seeds) : undefined, url: opts.url, idempotencyKey: opts.idempotencyKey })));
  discovery.command('serp').argument('<projectId>').argument('<jobId>').argument('<candidateId>').option('--num <number>', 'Results', '10').option('--idempotency-key <key>').action(async (projectId: string, jobId: string, candidateId: string, opts: any) => print(await discoveryCommands.serp(agentCtx(ctx), { projectId, jobId, candidateId, num: Number(opts.num), idempotencyKey: opts.idempotencyKey })));
  discovery.command('finish').argument('<projectId>').argument('<jobId>').requiredOption('--summary <text>').action(async (projectId: string, jobId: string, opts: any) => print(await discoveryCommands.finishResearch(agentCtx(ctx), { projectId, jobId, summary: opts.summary })));
  discovery.command('review').argument('<projectId>').argument('<jobId>').argument('<candidateId>').argument('<status>', 'shortlisted | hold | rejected | research_more').option('--reason <text>').action(async (projectId: string, jobId: string, candidateId: string, status: any, opts: any) => print(await discoveryCommands.reviewCandidate(ctx, { projectId, jobId, candidateId, status, reason: opts.reason })));
  discovery.command('bulk-review').argument('<projectId>').requiredOption('--candidates <csv>').requiredOption('--status <status>', 'shortlisted | hold | rejected').option('--reason <text>').action(async (projectId: string, opts: any) => print(await discoveryCommands.bulkReviewCandidates(ctx, { projectId, candidateIds: csv(opts.candidates), status: opts.status, reason: opts.reason })));
  discovery.command('cancel').argument('<projectId>').argument('<jobId>').option('--reason <text>').action(async (projectId: string, jobId: string, opts: any) => print(await discoveryCommands.cancel(ctx, { projectId, jobId, reason: opts.reason })));

  const maintenance = program.command('maintenance');
  maintenance.command('diagnostics').action(async () => print(await maintenanceCommands.diagnostics(ctx)));
  maintenance.command('backup').option('--destination <path>').action(async (opts: any) => print(await maintenanceCommands.backup(ctx, { destination: opts.destination })));
}
