export const KEYWORDS_MCP_SERVER_VERSION = '1.13.0';

export const KEYWORDS_MCP_TOOL_NAMES = [
  'remote_keyword_status',
  'keyword_demand_research',
  'serp_research',
  'serp_analyze',
  'keyword_treasury_save',
  'keyword_treasury_list',
  'site_structure_list',
  'site_structure_get',
  'site_structure_save',
  'research_session_create',
  'research_session_get',
  'research_session_list',
  'research_session_update',
  'serp_usage_status',
  'keyword_treasury_search',
  'site_structure_patch',
  'keyword_screen_batch',
  'keyword_research_pipeline',
  'theme_research_context',
  'theme_candidate_upsert',
  'theme_candidate_challenge',
  'seo_source_pool_context',
  'seo_source_get',
  'seo_source_save',
  'seo_source_scan_record',
  'trend_article_research',
  'market_signal_scan',
  'market_intelligence_research',
  'market_signal_snapshot_save',
  'market_signal_snapshot_compare',
  'marketplace_research',
  'search_gap_research'
] as const;
