export const SITES_MCP_SERVER_VERSION = '0.19.0';

export const SITES_MCP_TOOL_NAMES = [
  'remote_sites_status',
  'seo_agent_context',
  'seo_evaluator_list',
  'seo_evaluator_get',
  'site_registry_list',
  'site_registry_get',
  'site_registry_resolve',
  'site_registry_save',
  'site_direction_get',
  'site_direction_create',
  'site_direction_list',
  'site_direction_update',
  'seo_recovery_status',
  'seo_recovery_portfolio_update',
  'seo_recovery_site_update',
  'cloudflare_pages_site_status',
  'cloudflare_pages_set_preview_branch_exclusions',
  'cloudflare_pages_deployment_logs',
  'cloudflare_worker_set_subdomain',
  'cloudflare_worker_secret_recovery',
  'site_article_list',
  'site_article_get',
  'site_article_save',
  'site_metric_snapshot_list',
  'site_indexation_inventory_save',
  'site_indexation_inspect',
  'site_indexation_list',
  'site_indexation_summary',
  'site_indexation_snapshot_save',
  'seo_planning_digest_get',
  'seo_planning_digest_list',
  'seo_task_get',
  'seo_task_create',
  'seo_task_list',
  'seo_task_claim',
  'seo_task_heartbeat',
  'seo_task_update',
  'optimization_event_create',
  'optimization_event_list',
  'optimization_event_update',
  'optimization_context',
  'optimization_evaluation_context',
  'site_query_opportunities'
] as const;
